slsa-framework/slsa

README.md
Addresses two issues raised by @david-a-wheeler.
=> Small fixes 

README.md
Addresses the most critical piece of #40. Down the road, it might be good to further document how we use this date.
=> Add "definition version" date

README.md
As discussed on Friday, this PR adds a new level, 1.5, with guarantees between 1 and 2. It also cleans up some wording.
=> Add SLSA 1.5

README.md
Changes to requirements:
- Remove "Source Integrity", add immutable references to "Hermetic".
- Drop "Common" from SLSA 2 because it is likely expensive.
Clarifications:
- Split out "Ephemeral Environment" from "Isolation" (from #52).
- Explain that GH-generated merge commits meet Verified History (from #52).
- Clarify that all artifact references are immutable (from #52).
- Rename "Dependencies" to "Dependencies Complete" to avoid confusion.
- Define "SLSA level", "provenance", and "top-level source."
- Other minor cleanups.
=> Clarify SLSA requirements.

README.md
Minor changes to remove the notion that this is a "proposal" and instead
just describe SLSA as it is.
Also explain that levels 2-3 are likely to change in the future, rather
than using some sort of symbol (*) or term (provisional), since
technically all requirements are subject to change. It's just that 2-3
are more likely to change.
=> Remove "proposed" wording.

README.md, build-requirements.md, common-requirements.md, source-requirements.md
This PR provides a starting point for discussions of detailed requirements for source systems. It likely does not get everything right, but hopefully it shows the level of detail we're expecting.
=> Add detailed source requirements.

README.md
=> typofix: "reviewed"

README.md
=> Define SLSA 0.

controls/attestations.md, controls/survey.md
This is the new official name.
=> Rename signing-spec to DSSE.

README.md
Minor fix to avoid the use of double "build"
=> Remove extra "build"

walkthrough.md
Fixes #89. Thanks to @rtmorgan for reporting.
=> Fix typo within case study (SLSA 3 -> 4)

case-studies/README.md
=> new folder for community members to submit case studies

use_cases.md
Still very much draft.  Lots of work left to do.
=> Document some SLSA use cases

docs/_sass/minima/_custom.scss, docs/index.md
- New copy on `index` to explain the high-level ethos of the project
=> Improves comms around project ethos

README.md
Adding the initial seven steering members!
Signed-off-by: Dan Lorenc <dlorenc@google.com>
=> Add steering members.

docs/requirements.md
Fixes https://github.com/slsa-framework/slsa/issues/142
=> Fix incorrect SLSA level for retention

README.md
This should make it easier to get feedback where needed.
Signed-off-by: Tom Hennen <tomhennen@google.com>
=> Add shortcut to @ committee members

.gitignore, README.md
Signed-off-by: Dev Morgan <disfordisford@gmail.com>
=> Adds SLSA goose to /readme

docs/requirements.md
=> Use "build-as-code" terminology

docs/levels.md
=> Add build as code to levels page

docs/requirements.md
Fixes #127
Once this is in we can tag 0.1.
=> Make source control recommended at L1

README.md, docs/getinvolved.md
=> fix caps on Datadog

README.md, docs/getinvolved.md
=> Community meeting is bi-weekly, not bi-monthly.

docs/requirements.md
Per the discussion in #180, an attempt at defining strong authentication.
=> Define strong authentication

README.md
=> README: op SLSA link fix, mention slack room

docs/provenance/v0.2-draft.md
=> Fix typos in v0.2 draft spec

docs/provenance/v0.1.md, docs/provenance/v0.2-draft.md
This was discussed at today's community meeting. I took a stab at documenting what I think are the recommendations, but please review to see if you agree.
I believe @joshuagl @mlieberman85 were the ones who commented during the meeting, but I may remembering incorrectly.
=> Document conventions for 0.x

docs/provenance/v0.2.md
=> Fix arguments vs parameters in 0.1->0.2 pseudocode

docs/requirements.md
=> Update provenance references to v0.2

docs/_config.yml, docs/provenance/v0.2.md
The provenance specification v0.2 is now accessible via the navigation bar on the website.
Co-authored-by: Marco Franssen <marco.franssen@philips.com>
Signed-off-by: Brend Smits <brend.smits@philips.com>
=> Make provenance specification more accessible

docs/faq.md
Fix two broken links in `faq.md`.
=> Fix broken links in faq.md

docs/levels.md
Replaces https://github.com/slsa-framework/slsa/pull/232.
Signed-off-by: Alexander Thomas <athom@google.com>
=> Fix typo in SLSA level 3 description

docs/getinvolved.md
Signed-off-by: Kim Lewandowski <kim.m.lewandowski@gmail.com>
=> fixing meeting link to point to ossf community cal

docs/levels.md
I'm 99% sure "mant" was meant to be "many"
=> Typo correction

docs/_spec/v0.1/threats.md
Previously the doc said flatly that typosquatting was out of scope. But SLSA can be a partial mitigation, so we should clarify that.
Thanks @TomHennen for the idea. Tom, does this look good to you? If so, I'll then send it to the steering committee.
=> Explain how SLSA can help with typosquatting.

docs/_spec/v0.1/index.md, docs/_spec/v0.1/levels.md, docs/_spec/v0.1/requirements.md, docs/_spec/v0.1/threats.md, docs/community.md, docs/get-started.md, docs/index.md, docs/use-cases.md
This fixes the pages when rendered on GitHub and generally makes the source easier to read.
Preview: https://deploy-preview-14--marklodato-slsa.netlify.app/
=> Prefer relative links to simplify the content.

docs/community.md
Appears to be accidentally lost in 7799d442
=> Fix link to OpenSSF Community Calendar

README.md, docs/community.md
@kimsterv has replace @zakgreant on the steering committee.
=> Update steering committe: Zak -> Kim

docs/_spec/v0.1/levels.md
Signed-off-by: Nikolai Shields <nikolai@nikolaishields.com>
=> Fix minor typo in levels.md

controls/attestations.md
Update link to SPDX Predicate type spec
=> Update attestations.md - fix link

README.md, docs/community.md
@MarkLodato could you please review?
=> Update working group schedule to Thursdays

docs/_spec/v0.1/requirements.md
* the build and configuration are in text files
* the code is stored in a version control system
* the code is executed by a build service
Signed-off-by: Nathen Harvey <nathenharvey@google.com>
=> Clarify 'build as code'

docs/_posts/2022-04-08-blog-launch.md
=> Fix trailing whitespace on blog post (lint error)

code-of-conduct.md
=> Add missing contact address

docs/_posts/2022-06-15-slsa-ssdf.md
Add blogpost on SLSA + SSDF.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
=> Add SLSA+SSDF blogpost

docs/_sass/minima/_base.scss
Signed-off-by: Asra Ali <asraa@google.com>
The code text over the code background does not have enough contrast.
=> fix: code formatting color

docs/_sass/minima/_base.scss
Fixes regression from slsa-framework/slsa#400, match code block background with code word
=> Fix code color regression, match code block background with code word

docs/_posts/2022-06-20-slsa-github-workflows.md
Signed-off-by: Asra Ali <asraa@google.com>
Now that it's released, update blog post
=> update: blog post with image of starter workflow

docs/get-started.md
Signed-off-by: Laurent Simon [laurentsimon@github.com](laurentsimon@github.com)
/cc @asraa @MarkLodato  @ianlewis @joshuagl
=> ✨ Recommend the slsa-github-generator for SLSA3

docs/index.md
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Update Trishank's role

.github/workflows/lint.yml
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>
=> fix: update tags for renovatebot

docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
Signed-off-by: Ian Lewis <ianlewis@google.com>
=> Escape curly braces in generic generator blog post

docs/community.md
It's technically every 4 weeks, but "monthly" is good enough for this doc. The actual cadence and details are in the linked notes doc.
=> Update bi-weekly meeting to monthly

docs/spec/v1.0/levels.md, docs/spec/v1.0/requirements.md
- Fix broken link in v1.0 levels.md
- Clean up wording of intro to v1.0 requirements.md
=> Fix broken link and clean up wording in v1.0

docs/spec/v1.0/levels.md
Fixes #523.
/cc @lehors @06kellyjac
=> v1.0 levels: clarify "local modifications"

docs/spec/v1.0/index.md, docs/spec/v1.0/principles.md
Addresses the following issues for v1.0:
-   Fixes #106.
-   Partially addresses #130. Future PR needs to integrate this concept into levels.md and requirements.md. (I'm waiting for the outstanding PRs for those files to be submitted first.)
Preview: https://deploy-preview-528--slsa.netlify.app/spec/v1.0/principles
=> SLSA v1.0: add Key Principles page

docs/spec/v1.0/levels.md
The additional requirements at build L2 help improve trustworthiness, not accuracy per discussion 
https://github.com/slsa-framework/slsa/pull/529/commits/d3b931f366ef2e5d765f3a17c02c94d979c35938#r1014411226
=> Address unresolved review comment in #529

docs/spec/v1.0/requirements.md
Related to issue https://github.com/slsa-framework/slsa/issues/321
Looking at combining ephemeral and isolated l3 req into one. 
Appended two "Should not" items as recommendations (not requirements)
=> SLSA v1.0: Combine requirements- ephemeral and isolated

docs/_sass/minima.scss, docs/_sass/minima/_base.scss
Changes in this PR:
- Update styles for inline code HTML elements
=> Inline code styling fixes

docs/get-started.md, docs/spec/v0.1/faq.md, docs/spec/v1.0/faq.md
This PR adds some information about in-toto and its relationship to SLSA.
=> Add information about in-toto to the SLSA website

docs/_layouts/standard.html, docs/_sass/minima/_custom.scss, docs/use-cases.md
PR contains changes:
- Update paragraph spacing
- Update ordered/unordered list spacing
- Update ordered/unordered list bullets/number visibility
- Update ordered lists to use number, alpha and roman symbols when nested
Fixes https://github.com/slsa-framework/slsa/issues/335
=> Paragraphs, Unordered List and Ordered List Spacing

docs/spec-stages.md
Remove reference to use in production left to the version number in line with discussion on PR #552 at: https://github.com/slsa-framework/slsa/pull/552/files/a040cafa72fed25b718f52a0b288d552868faae7#r1059504377
=> Fix definition of Stable stage

netlify.toml
Update config to render drafts and future posts in Netlify previews.
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>
=> ci: Preview drafts and future posts

docs/_data/nav.yml, docs/_includes/header.html, docs/_includes/nav-level.html, docs/_includes/nav.html
Separate the SLSA spec pages from the others within their own submenu.
=> Reorg specifications menu

docs/spec/v1.0/requirements.md
=> Fix typo in requirements section

docs/provenance/v1/index.md
This should have been changed in #582.
=> Provenance v1: fix v0.2->v1 for systemParameters

docs/spec/v0.1/faq.md, docs/spec/v1.0/faq.md
=> Fix relative link from FAQ to example.md

docs/community.md
This PR Proposes changes to add up the [recent talk from Ian Lewis](https://youtu.be/32IhwdAe0yI) about SLSA & guac in CloudNativeSecurityCon 2023 - Seattle
=> :sparkles: update recent talk from Ian Lewis

docs/provenance/v1.md, docs/spec/v1.0/faq.md, docs/spec/v1.0/levels.md, docs/spec/v1.0/requirements.md, docs/spec/v1.0/terminology.md, docs/spec/v1.0/verifying-artifacts.md
Overall this PR resolves the low-hanging fruit TODOs. Many of them weren't adding much value so I simply deleted them, while others were resolved to actually do the thing described.
See individual commits for more specific changes.
Related: #533
=> SLSA v1: resolve many outstanding TODOs

docs/_layouts/specifications.html
It's been bugging me for a while and @ianlewis's comment on PR #626 gave me the incentive to try and fix it.
Someone more fluent than me in modern CSS and tailwindcss can probably do better than me (my CSS days go back to CSS2 circa 2008! :-) but I think this is already an improvement.
=> Add a scrollbar to the TOC sidebar when getting long

docs/spec/v1.0-rc1/index.md
Addresses https://github.com/slsa-framework/slsa/pull/640#discussion_r1117678402. Thanks @di for catching.
=> Fix version 1.0-rc1 reference on index page

docs/_posts/2023-02-24-slsa-v1-rc.md
Add slsa.dev blog post announcing v1.0 release candidate.
Fixes #606.
=> Add slsa v1 rc blog post

docs/index.md
=> Use relative link to blog post on main page

docs/_includes/header.html, docs/_sass/minima/_custom.scss
- Updated header layout to not overflow the draft banner at certain screen sizes
Example URL: https://deploy-preview-666--slsa.netlify.app/spec/v1.0/
=> Fix Draft Banner Layout

docs/_config.yml
This may not completely remedy the situation presented in #689, but it should at least be a little bit better.
=> Change social image to be slightly smaller

docs/_includes/nav-level.html, docs/_includes/nav.html, docs/_sass/minima/_custom.scss, docs/_sass/minima/_layout.scss
There is no user-visible difference.
- Remove unnecessary HTML classes.
- Remove unused liquid variables.
- Remove duplication between nav.html and nav-level.html.
- Combine relevant SCSS bits into one file.
=> Simplify implementation of nav template/css

docs/spec/v1.0/requirements.md
Describe which part of the provenance MUST be complete and which part is best effort for each level.
=> Review requirements related to provenance completeness for L2 and L3.

docs/_data/versions.yml, docs/spec-stages.md
This addresses [Issue #20 opened in the governance repo](https://github.com/slsa-framework/governance/issues/20)
=> Align spec stages with Community Specification License framework

docs/spec/v1.0/requirements.md, docs/spec/v1.0/threats.md
Part of the confusion mentioned in https://github.com/slsa-framework/slsa/issues/657 was related to the separation between producer actions and build system actions for achieving a desired SLSA build level. While there is likely additional clarification needed, this is at least a step to get there.
=> Clarify actions between producer and build system

docs/verification_summary/v1.md
For consistency with Provenance.
Fixes #741.
=> VSA v1: convert to lowerCamelCase

docs/spec/v1.0/requirements.md, docs/spec/v1.0/verifying-systems.md
* Fixed vestigial section references
* Provenance accuracy is part of integrity
* Clarified producer and build system relationship
@jchestershopify, can you take a look at these changes as well?
=> Add some clarification related to #653.

docs/_includes/onepage.liquid, docs/spec/v1.0/onepage.md
=> Update onepage to match latest files

docs/verification_summary/v1.md
=> VSA v1: make dependencyLevels optional

.gitignore, docs/README.md
Update README.md to explain the `--incremental` (and while we're at it, `--livereload`).
Also gitignore the file generated by jekyll in incremental mode.
=> (dev) Support jekyll `--incremental`

docs/community.md
I recently changed employer :-)
=> Update Joshua's affiliation

docs/provenance/v1.md
"Verifying Artifacts"  is currently
`/spec/v1.0/verifying-artifacts.md`
Change it to `/spec/v1.0/verifying-artifacts`.
The slsa.dev server doesn't recognize `.md` extension.
=> fix a broken link

docs/provenance/v1.md
=> Minor grammar change

docs/spec/v1.0/faq.md
An attempt at answering this frequent source of confusion for users, as suggested in https://github.com/slsa-framework/slsa/issues/691#issuecomment-1504083988
See the new FAQ item at https://deploy-preview-827--slsa.netlify.app/spec/v1.0/faq#q-how-does-slsa-and-slsa-provenance-relate-to-sbom
=> Add FAQ item on SBOMs

.github/CODEOWNERS
I'm still around, I just haven't been reviewing this stuff.  Other folks are looking out for that.
=> I'm no longer the appropriate reviewer for provenance & VSAs.

.github/workflows/enforce-tags.yml, CONTRIBUTING.md
- Add PR title/description requirements.
- Clarify review requirements and merge etiquette.
- Enable workflow to enforce PR title requirements.
fixes #821
=> impl: Update CONTRIBUTING.md.

.github/workflows/enforce-tags.yml, CONTRIBUTING.md
=> impl: Remove dashes from types in PR name lint

MAINTAINERS.md
Proposing myself to be added to the SLSA maintainers list based on my participation in the community.
=> impl: self-add Andrew M to SLSA maintainers

docs/spec/v1.0/threats-overview.md, docs/spec/v1.0/threats.md, docs/spec/v1.1/threats-overview.md, docs/spec/v1.1/threats.md
=> editorial: Clarify that SLSA does not address all represented threats

MAINTAINERS.md
I'd like to propose making myself a maintainer.
I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer).
=> nonspec: Add TomHennen as a maintainer

docs/spec/draft/source-requirements.md
These issues have all been closed, removing them.
=> editorial: draft: Remove closed issues from source-requirements

README.md
This PR updates the Attested Build Environments track workstream shepherd and reference.
=> impl: Replace Chad with @paveliak as BuildEnv track shepherd

MAINTAINERS.md
I'm proposing myself as a maintainer for the SLSA spec. I've been active generally for some time now but have been more involved recently in the source track. Please let me know if there are concerns, thanks!
=> nonspec: Add adityasaky as a maintainer

docs/spec/draft/use-cases.md, docs/spec/v0.1/use-cases.md, docs/spec/v1.0-rc1/use-cases.md, docs/spec/v1.0-rc2/use-cases.md, docs/spec/v1.0/use-cases.md, docs/spec/v1.1/use-cases.md
=> fix: Update link to SUSE case study

docs/community.md
Follow up from https://github.com/slsa-framework/governance/pull/25
=> content: Update website with current steering committee

docs/spec/draft/future-directions.md
=> content: Update future directions page to include the build env track

docs/spec/draft/source-requirements.md
Fix misspelling of attestations
=> fix: attsetations -> attestations

README.md
updating shepherds to what (I believe) are the current folks.
=> nonspec: readme: update shepherds

docs/spec/draft/threats.md
Provides more detailed examples of cache poisoning leveraging @MarkLodato's helpful comment in #1303.
Also link to a detailed real-world example.
Fixes #1303.
=> content: draft: Clarify cache poisoning example

docs/_posts/2025-04-04-slsa-v1.1-rc2.md
This adds a blog post announcing the publication of V1.1 RC2.
=> blog: Add blog post announcing v1.1 RC2

docs/spec/v1.1-rc2/future-directions.md
addressing minor spelling errors.
=> fix: 1.1-rc2: address minor typo

docs/spec/draft/about.md, docs/spec/draft/attestation-model.md, docs/spec/draft/distributing-provenance.md, docs/spec/draft/future-directions.md, docs/spec/draft/levels.md, docs/spec/draft/principles.md, docs/spec/draft/provenance.md, docs/spec/draft/terminology.md, docs/spec/draft/use-cases.md, docs/spec/draft/verifying-artifacts.md
Align the draft version of the spec with the latest v1.1-rc2.
=> fix: Apply fixes from PR 1319 and 1320 to draft

.vscode/settings.json
In order to enable more consistent line breaks, proposing an initial .vscode/settings.json file that will indicate when a line gets to 80 characters.
Additional common development settings can be added in the future.
=> impl: create vscode settings file

docs/spec/draft/source-requirements.md
This PR updates the source requirements documentation to reflect revised identifiers and branch consumption rules while adding clarification about tag management.
Removed outdated "Canonical location" and "Immutable Revisions" rows.
Revised repository and revision ID definitions for consistency.
Updated branch continuity language and added a new section on tag hygiene.
=> content: draft: update canonical location, revisions, branches wording

docs/spec/draft/source-requirements.md
Similar to the build track, the requirements for organizations in the source track are to choose a source control system which is capable of achieving the desired levels.
=> content: draft: Simplify source organization requirements

docs/spec/draft/onepage.md
Adds new pages attested-build-env-levels and verifying-source to the draft single page view.
=> fix: Add missing files to draft onepage.md

docs/spec/draft/source-requirements.md
And clarify they're protected by the org's change mangagment process.
=> content: draft: Rename 'Branches' to 'Protected Branches'

docs/spec/draft/source-requirements.md
This is a strict copy edit pass. 
There were a few typos, and an attempted simplification of the objective.
=> content: draft: source track: cleanup objective section

docs/spec/draft/verified-properties.md
it seems that Jekyll is adding some titles too
=> fix: draft: too many titles

docs/spec/draft/build-track-basics.md, docs/spec/draft/source-requirements.md
* Adds a simplified table that describes the levels.
* Mirrors [this table](https://slsa.dev/spec/draft/build-track-basics#:~:text=Track/Level,Focus)
* Updates the Summary/Intended for/benefits to be tables [as seen here](https://slsa.dev/spec/draft/build-track-basics#build-l0-no-guarantees)
* Update build track basics to mention the source track exists now.
fixes #1111
=> content: draft: tabularize source track summary

docs/spec/draft/source-requirements.md
Adds anchor links to each row in the source requirements.
I'm not yet sure how well this is going to look.  Might need further tweaking.
fixes #1433
=> style: Add basic anchor links to source requirements

docs/spec/draft/tracks.md
Adding a placeholder summary of the Dependency Track, in anticipation of the draft being published
=> content: draft: Adding Dependency Track to tracks.md

docs/spec/draft/tracks.md
content: draft: linking to draft dependency track page
=> style: draft: linking to draft dependency track page

docs/spec/draft/source-requirements.md, docs/spec/draft/verifying-source.md
fixes https://github.com/slsa-framework/slsa/issues/1462
* Following RFC 2119
* Clarfiied subject.uri
* source_refs -> sourceRefs
=> content: draft: fix various source VSA issues.
