slsa-framework/slsa

- README.md
At SLSA 3, we now recommend reproducible builds. This is not a strict requirement because not all builds can become reproducible, as explained in the text. Once we write the detailed requirements, we will likely want to somehow explain that reproducible should be the default, while still allowing individual projects to opt-out.
The reason for adding this recommendation is to move the industry towards reproducibility, which is a generally useful property. By having it as the "default" path, most software will just go with the past of least resistance rather than opting out.
Note that this does not require *verifying* the reproduction for security (#5). Instead, the builder just claims that it was reproducible, presumably by building it twice and making sure that the output is identical.
> Add Reproducible as a recommendation at SLSA 3

- README.md
Looks like Google took down the free copy of the book, so we just have
to link to the landing page. That also means we can't use that as one of
our "benefits of reproducible builds" links. :-(
Fixes #25.
> Remove broken links to SRS Book PDF (#25).

- README.md
We can use tags to indicate prior versions, instead of listing it
directly in the doc.
Add a reminder to the reader that this is stil in flux, replacing the
old reminder about community feedback.
> Replace "definition version" with note (#19)

- README.md
SLSA 1 is now fully defined and has lower requirements.
Major changes:
- Replace "Readability" with "Version Control", removed at SLSA 1.
- Add "Build Service", required at SLSA 2.
- Split "Provenance" into three rows, and do not require tamper
resistance (e.g. signing) until SLSA 2.
- Remove "Enforcement". This is now orthogonal to the level.
- Do not require "Logging", "Policy", or "Common" until SLSA 2.
- Simplify "Policy" to not talk about build entry point.
Minor changes:
- Rename "Change History" to "Verified History".
> Rework SLSA requirements.

- README.md
The PDF has been made available again at the same location, so revert 85861abf2e7f68e685dd611c43833e472a1d2896 which removed the link.
> Add back the link to the SRS book PDF

- README.md
This makes the table easier to read since one box is not a simple
checkmark instead of a word.
> Rename "Retained" to "Retained Indefinitely"

- README.md
- build-requirements.md
Fully define all build requirements. The document still needs an introduction, including diagram, threat model, and high-level description.
Add a "Parameterless" requirement to SLSA 4, which we forgot previously.
> Define build requirements; add "Parameterless".

- README.md
> Clarify where the sha256 comes from in the Alpine build process.

- README.md
- common-requirements.md
- source-requirements.md
In the "Level requirements" section, add links in the table from each
requirement the corresponding entry in the detailed source/build/common
doc, and remove the duplicate "summary" descriptions below it. This
avoids confusion and the need to keep the two in sync, at the cost of
making it slightly harder to skim. This seems like a worthwhile
tradeoff.
Also convert the table to pure Markdown, for two reasons:
- To make the table easier maintain.
- To allow us links to work in both GitHub and GitHub Pages. This is
achieved by the jekyll-relative-links plugin, which only works with
markdown links, not HTML links.
The downside to converting to Markdown is that we can't use rowspan and
colspan. This isn't too bad of a hit to readability.
> Linkify reqs table; remove duplicate descriptions.

- requirements.md
* Use the same formatting as the Build requirements, which is much easier to read.
* Reformat the Build requirements table as explained in 7fafe1e8.
> Convert Source and Common requirements to tables

- README.md
This makes it easier to open an issue, especially from slsa.dev.
> Add link to GitHub issues.

- README.md
* When viewing the page on GitHub, there is now a link telling the reader that it is best viewed at https://slsa.dev. This does not show up when rendered via GitHub Pages.
* Remove the duplicate "SLSA is..." paragraph and the obsolete "Trusted persons" footnote. The former is already found a few paragraphs up, and the latter is no longer referenced.
* Clean up Markdown formatting, namely newlines at end of line, and use a reference link to "salsa" to make the Markdown easier to read.
> Link to slsa.dev, remove duplicate content, and clean up formatting.

- .github/workflows/lint.yml
As per the [GitHub doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions), let's follow the principle of least privilege and make the tokens read only.
Can be detected with:
```
scorecard --repo=github.com/slsa-framework/slsa/ --checks Token-Permissions --show-details
...
!! token-permissions/github-token - no permission defined in .github/workflows/lint.yml
```
AFAIK, the action used need not write access.
> Make workflow permissions read only

- .github/workflows/lint.yml
- .gitignore
- package-lock.json
- package.json
This makes it easier for other developers to run markdownlint, and
checking in package-lock.json ensures that we're all using the same
version.
Futhermore, this commit calls `npm run lint` directly instead of using
the GitHub Action because the action doesn't seem to be working.
Example in action: https://github.com/slsa-framework/slsa/pull/84/checks?check_run_id=2955334338
> Set up `npm run lint` to call markdownlint.

- .github/dependabot.yml
As we now keep npm packaging metadata in the repository, have dependabot monitor it and notify of updates.
> Have dependabot keep npm modules up-to-date also

- README.md
Reformat the attacks table to make it easier to maintain: Remove unnecessary closing `tr` and `td` tags. Merge short columns onto one line. Separate each row with a blank line. Break lines at natural boundaries.
Fix a stale link to build-requirements.md, which (a) was an absolute link instead of relative, (b) pointed to a file that has since been deleted, and (c) didn't work on [slsa.dev.](https://slsa.dev) since the jekyll-relative-links plugin only works on Markdown links, not HTML links.
> Reformat the attacks table, fix link to reqs.

- requirements.md
This is a very minor stylistic change. Instead of using "MUST disallow" as the negative, I suggest using "MUST NOT allow". This places the emphasis onto the RFC 2119 term and makes visual scanning easier.
> Lay disallowance emphasis on RFC2119 MUST NOT

- requirements.md
This change updates the "Identifies Artifact" requirement to allow multiple hashes to be computed for artifacts. This is already a capability of the In-Toto attestation format.
> Explicitly allow multiple provenance hashes

- .github/workflows/lint.yml
Dependabot automated version bumps only update the hash, not the
comment, so the comment is likely to get stale. Example: #102.
> Remove version comments from pinned actions.

- CONTRIBUTING.md
- code-of-conduct.md
- community/README.md
Fixes #112 
I took a first pass at adding some contributor documentation to the repo. This includes:
- a copy of the OpenSSF Code of Conduct
- contributor documentation describing DCO and markdownlint
We should also add a GitHub Action to ensure commits have include a DCO: https://probot.github.io/apps/dco/
> Initial contributor documentation

- docs/requirements.md
The link at https://slsa.dev/requirements#provenance-requirements is broken.
> Fix link to in-toto provenance

- docs/provenance/v0.1.md
The examples previously only had 'recipe', now they also have
'materials'. Note that they are not complete and exclude 'metadata'.
Refs #143
Signed-off-by: Tom Hennen <tomhennen@google.com>
> Add git materials to examples.

- docs/provenance/v0.1.md
- docs/requirements.md
* Require build instructions to be tracked at **all** levels.
* Lets people know how a build was produced.
* Should support all build methods without requiring architectural changes.
* If we adopt [this document](https://docs.google.com/document/d/1fLtR5-AfauKlgTvQ1yRrupIZVnX3YqBhAjO_2X3d4qE/edit#heading=h.q2vn2vj1ydg5) as level motivation (#111) then we may only need to require build instructions at level 2+ or 3+.  We can easily relax this requirement later, while making the requirement more strict would be more difficult.
* Require config-as-code at L3+.
* Allows people to review the details of how builds are performed.
* Can require changes to how builds are performed to be reviewed by additional parties.
* Tracks changes to how builds are produced over time.
* Provides an easier …
> Require config as code at levels L3+

- docs/requirements.md
As discussed in #129 this requires source repositories to be identified at level 2+.
Doesn't address dependencies yet...
Signed-off-by: Tom Hennen <tomhennen@google.com>
> Add "Identifies Source Code" requirement

- docs/_includes/footer.html
In the footer "View on GitHub" link, we now link to the specific
Markdown page rather than the top-level site. This makes it easier to
edit the page and view the source.
> Link to specific blob in GitHub.

- controls/survey.md
https://github.com/in-toto/attestations should be https://github.com/in-toto/attestation
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> Broken link

- docs/provenance/v0.1.md
- docs/provenance/v0.2-draft.md
* Rename 0.2-alpha to 0.2-draft to make it more clear that it is unstable. (Suggested by @joshuagl.)
* Add an explicit warning that 0.2 draft spec is subject to change.
* Add links to the other versions of the spec to allow readers to easily jump between versions.
* Remove boilerplate from the introductory material so that it is easier to read.
> Provenance spec: rename to 0.2-draft, add warning, link between versions

- docs/provenance/v0.2-draft.md
- Note the addition of build configuration in the summary. (It's not
part of "refactor to aid clarity.)
- Add a brief rationale for adding build configuration.
- Note that the model has not changed.
- Fix typo.
- Keep all the "refactor" lines together.
> Expand the v0.2 changelog entry.

- docs/provenance/v0.2-draft.md
This PR makes small language improvements, but mostly intends to clarify the text's use of "attestation" in the context of in-toto.
-  Switch ambiguous "claim" to "attestation": claim is one of the terms that [was considered](https://github.com/slsa-framework/slsa/blob/main/controls/attestations.md) in lieu of attestation, and i've understood to be synonymous here. I found seeing it here added confusion between attestation, claim, statement, etc.
-   Add pre-requisite section, to provide reference for the terminology:
- in-toto attestations
- slsa attestations
- Clarify what a "Statement" is, in this in-toto context.
I hope these are straightforward clarifications, they are not intended to open up a big conversation :)
> Small improvements to provenance v0.2 draft

- docs/_sass/minima/_custom.scss
- docs/threats.md
Improve the display of threats so that it is easier to read by displaying as table rows, where each row is clickable to get details. Also highlight the SLSA level that addresses each threat.
Preview: https://marklodato.github.io/slsa/threats (The "view file" on GitHub doesn't use CSS, so it doesn't look as pretty)
> Render the threat lists as a collapsible table

- docs/provenance/v0.2-draft.md
This makes it easier to understand the mapping between versions.
@marcofranssen Does this answer your question?
> Provenance 0.2: add pseudocode to migrate from 0.1

- docs/provenance/v0.1.md
- docs/provenance/v0.2-draft.html
- docs/provenance/v0.2.md
Rename v0.2-draft to v0.2, and add a redirect from v0.2-draft to keep old links working.
Note: We use a raw HTML redirect rather than jekyll-redirect-from because `redirect_from` clutters up the top of v0.2.md and `redirect_to` would keep v0.2-draft.md, which in turn would break git's move file
detection.
> Mark provenance v0.2 as final (non-draft)

- docs/provenance/v0.2.md
The `title` frontmatter attribute adds an additional title to the page due to our template. The simple solution is to rename the `h1` title to match what we want in the header.
The proper fix would be to update our template so that we can manually set the title in the navbar.
> Fix duplicate page title of provenance after #218

- README.md
- docs/getinvolved.md
- Fix the address on slsa.dev, which incorrectly pointed to the OpenSSF WG mailing list instead of SLSA's.
- Use more direct wording to make it easier to read.
cc: @devmoran
> Fix link to mailing list and update wording

- docs/_config.yml
- docs/_includes/google-analytics.html
This requires upgrading to the latest google analytics code because the version on GitHub Pages is outdated.
Requested by @devmoran, who will use this to measure improvements to the site.
I believe I granted Analytics access to @devmoran, @trishankatdatadog, @inferno-chromium, and @joshuagl but please let me know if you do not have access.
> Enable Google Analytics on slsa.dev

- CONTRIBUTING.md
- README.md
- docs/getinvolved.md
Sort the steering committee list alphabetically.
Reference the new @slsa-framework/slsa-steering-committee alias.
In the contributor guide, clarify that only significant changes to the spec require two steering committee members to review, and that others can be approved by a single reviewer. In particular, document that it's OK for author and reviewer to be from the same org.
(This documents what was discussed in an email thread. It would be great if other steering committee members can weigh in, in case they disagree.)
> Clean up steering committee list; clarify approval expectations for this repo.

- docs/provenance/v0.2.md
There are several mentions of invocation.sourceConfig in the descriptions
of fields in the provenance format. However, the field name is
configSource.
Signed-off-by: Joshua Lock <jlock@vmware.com>
> provenance: fix name of configSource in descriptions

- docs/provenance/v0.2.md
`invocation.configSource.uri` should be of type ResourceURI.
> Fix a typo in provenance definition.

- docs/_includes/google-analytics.html
This stops cookies from loading so that we don't need a GDPR cookie banner.
This is an alternative to #237. I don't know how much this hampers our analytics, but I agree with @david-a-wheeler that should not do anything that requires consent.
> Run Google Analytics in "denied consent" mode.

- README.md
Add the newly creating SLSA steering committee mailing list to the README file to allow people to easily contact the steering committee. This is not on the slsa.dev site since we'd prefer users to go through public channels.
Also fix the GitHub team name (no "teams/") in the README.
**Question:** Should it also go on slsa.dev?
> README: Add steering committee list, fix GH alias.

- docs/_includes/specifications-list.html
- docs/_spec/faq.md
- docs/_spec/v0.1/index.md
- docs/_spec/v0.1/levels.md
- docs/_spec/v0.1/requirements.md
- docs/_spec/v0.1/threats.md
Similar to e56c388 (#270), but for the list of subpages in /spec/v0.1/index. This change replace the "automatic" code with a manual list, which is much easier to understand and maintain.
No content change. The only HTML change is to switch from absolute to relative links and to eliminate empty `<li>` elements.
NOTE: Neither the original nor new code correctly handled displaying more than one specification version. This commit adds a TODO making it clear that it doesn't work.
The old and new version result in identical HTML except as noted above, ignoring one whitespace change and build timestamps on posts.
```bash
$ git checkout main
$ bundle exec jekyll build
$ mv _site /tmp/old_site
$ git checkout spec-list
$ bundle exec jekyll build
$ diff -u {/tmp/old_site,_site}/spec/v0.1/index.html …
```
> Simplify the specifications list template.

- README.md
- Old invite points to hangouts instead of zoom. Updating this to point to updated calendar instead. 
- Update parent WG name
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Update meeting calendar link and readme info

- docs/_spec/v0.1/requirements.md
Previously there was some confusion on whether an actual permalink is required (e.g. a URI) rather than a unique identifier. The intention was simply to allow joining of other data sources, not to require a URI, so hopefully the new wording makes this more clear.
The intent is *NOT* to now require a unique ID instead of a permalink, but rather to be more generic in what meets the requirement. In particular, if something already met the requirement before, it should still meet the requirement after this PR. Reviewers, please read carefully and offer suggestions if this doesn't read that way.
@bobcatfish does this help?
> Replace "permalink to debug logs" with "unique ID"

- docs/_spec/v0.1/threats.md
schneider.dev is down and, sadly, unlikely to come back. This patch
replaces the link to Zach Schneider's explanation with a link to the
official npm analysis of the incident.
Fixes #314
> threats: replace link to event-stream incident

- docs/_config.yml
- docs/_includes/head.html
- docs/index.md
This continues using the jekyll-seo-tag plugin, which I think might be generating incorrect tags. The preview does not work on the various debug tools (e.g. twitters), but at least the description is better than before, and an image tag is generated. Let's submit this and see if it's any better on the real thing.
Partial fix for #274.
> Fix social preview

- docs/provenance/v0.2.md
The provenance spec explicitly dictates handling of null or unset values for certain object and array fields, but not all. With this change null or unset values of these types will be uniformly treated as empty.
> Clarify null vs. unset for optional fields

- docs/community.md
Link to the Google Groups mailing list and Slack from the community page. These are currently only linked to from the README and do not appear on slsa.dev
> Add discussion links to community page

- docs/verification_summary/index.html
- docs/verification_summary/index.md
- docs/verification_summary/v0.1.md
Fixes #107 by creating an attestation that indicates a `verifier`
has determined that the specified `subject` artifact(s) meets the
indicated SLSA level.
In addition this attestation also indicates the minimum aggregate
SLSA level met by the dependencies used to build the artifact
which can help to address #61.
This leaves a number of things up to the user:
* What it means to evaluate an artifact against policy. (See #46)
* How to communicate the attestations required to create this
attestation.
* How to debug failures
I borrowed heavily from slsa.dev/provenance in terms of
formatting/documentation.
If desired I can provide detailed algorithms for how the minimum_*
fields could be computed.
This attestation is based on work done by @AdamZWu.
Signed-off-by: Tom Hennen …
> Document a SLSA verification summary attestation.

- CONTRIBUTING.md
The documentation of the proposal document is found in https://github.com/slsa-framework/slsa-proposals/pull/1.
Part of the implementation for #296.
> Add proposal process to CONTRIBUTING.

- docs/_data/nav.yml
- docs/_includes/nav.html
It was a bit confusing why "Provenance" got its own top-level menu, especially since it too is a specification. Now all specs are under a single menu. This makes the top-level nav a bit cleaner.
Insert a horizontal rule to differentiate between the SLSA ladder and the attestations formats. Without that, the organization of the menu is a bit unclear.
Add a link to VSA. Fixes #334.
> Move "Provenance" under specifications menu, and add link to "VSA"

- docs/verification_summary/v0.1.md
Previously the bullet didn't render correctly and the spacing was messed
up.
> Fix "Change history" rendering of VSA page

- .github/dependabot.yml
Our Gemfile is in the docs directory, not the root directory.
Decrease all the frequencies to weekly (not daily) to slightly reduce
the amount of PR spam we get.
> dependabot: fix bundler, decrease freq to weekly

- docs/_posts/2022-05-02-slsa-sbom.md
SLSA + SBOM blogpost
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Add SLSA + SBOM blogpost

- docs/_layouts/post-list.html
- docs/_layouts/post.html
- docs/_posts/2022-04-08-blog-launch.md
- docs/_posts/2022-04-11-slsa-is-no-free-lunch.md
- docs/_posts/2022-05-02-slsa-sbom.md
- docs/_sass/minima/_layout.scss
Context: https://github.com/slsa-framework/slsa/issues/309#issuecomment-1113559601
Add a "views expressed disclaimer" on guest posts. 
Clean up the styling of blog posts:
- Smaller header with white background.
- Format the date to look a bit nicer.
Preview: https://deploy-preview-379--slsa.netlify.app/blog/2022/04/slsa-is-no-free-lunch
[...]
> Blog: clean up styling, add banner for guest posts

- docs/_spec/v0.1/requirements.md
Refine the text to make it clearer that the recipe and configuration must
be verifiably traceable to text files in an SCM, not necessarily fetched
from the SCM directly by the trusted control plane.
Fixes #368
> Refine 'build as code' requirement description

- docs/_spec/v0.1/terminology.md
Proposing a fix to the live document
> docs: fix typo in description of the build model

- docs/provenance/v0.2.md
GitLab recently released version 15.1 of their runner which introduced the ability to generate SLSA provenance for GitLab jobs that produce artifacts. https://docs.gitlab.com/ee/ci/runners/configure_runners.html#artifact-attestation
I updated the provenance page to reflect this. I slotted it in the middle of the GitHub and Google Cloud examples.
- Kept GitHub's example above because it seems more prevalent 
- Put it above Google Cloud because it is a real life example and not for demonstration purposes
_This is my first open source submission ever - please let me know how I can improve this PR.  I tried to follow the contributing guidance as close as possible._
> Add GitLab Provenance Example

- docs/get-started.md
Signed-off-by: pxp928 <parth.psu@gmail.com>
Adding OpenSSF [FRSCA](https://github.com/buildsec/frsca) to the getting started page as another example implementation of how to obtain the various SLSA levels. FRSCA is an implementation of the CNCF's [Secure Software Factory Reference Architecture](https://docs.google.com/document/d/1FwyOIDramwCnivuvUxrMmHmCr02ARoA3jw76o1mGfGQ) which is based on the CNCF's [Software Supply Chain Best Practices White Paper](https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/CNCF_SSCP_v1.pdf). 
Currently FRSCA is SLSA level 2 but in the coming weeks will be at SLSA level 3/4 with the addition of Tekton + Spire.
> Adding FRSCA in getting started

- docs/_spec/v0.1/requirements.md
fixes #414 - don't accidentally force implementors to use digital
signatures to prove non-falsifiability.  Instead, leave things open
enough that other implementations are acceptable.
> Changes wording of non-falsfiability requirement

- docs/_layouts/standard.html
- docs/_sass/minima/_custom.scss
The proper fix would be to fix the CSS, but for now the lack of inter-paragraph spacing (#335) is highly distracting so this is a cheap fix.
Preview: TODO
> Hack to fix paragraph spacing

- docs/_layouts/specifications.html
- docs/_layouts/standard.html
While playing around with layout for the Software attestations page in #438 I discovered that the `hero_text` did not support Markdown formatting. This PR enables support for Markdown in the `hero_text`. As I ultimately did not need it for #438 I pulled it out into a separate PR to see whether it's considered useful?
> RFC: Support markdown in hero_text for specification and standard?

- .markdownlint.yaml
- docs/example.md
- docs/provenance/v0.1.md
- docs/provenance/v0.2.md
- package-lock.json
- package.json
- Update dependency markdownlint-cli to v0.32.1 (#442)
- Remove unused link definitions
- Remove broken link from example.md
- Temporarily disable markdownlint MD051 and MD053, which are broken right now
> Fixes to support markdownlint v0.32

- CONTRIBUTING.md
Dependent on approval for https://github.com/slsa-framework/governance/pull/13/ 
Signed-off-by: Melba <101211710+melba-lopez@users.noreply.github.com>
> Added line to include link for SLSA Blog Criteria

- netlify.toml
The old setting broke the production deploy (but not previews).
Context: #266 
Tested: https://62e962f428e78400082b7a85--marklodato-slsa.netlify.app/
> Fix Netlify build by removing JEKYLL_ENV

- docs/verification_summary/v0.2-draft.md
Introduces `resource_uri` field in predicate to hold the resource URI used for verification, instead of the statement field `subject.name`.
> Create verification summary specification v0.2

- docs/verification_summary/index.html
- docs/verification_summary/index.md
- docs/verification_summary/v0.2.md
Adds `input_attestations` to fix #387.
Also takes VSA v0.2 out of draft status.
> Add `input_attestations` to VSA and bump up to v0.2

- docs/_data/nav.yml
The nav bar was pointing at an older version of the VSA spec. We don't actually need the provenance or vsa links to include the version number since we have other redirectors in place to send folks to the latest version anyways.
Signed-off-by: Tom Hennen <tomhennen@google.com>
> Nav bar should not include versions in spec links

- docs/community.md
- docs/notes/community.md
- docs/notes/index.md
- docs/notes/positioning.md
- docs/notes/spec.md
- docs/notes/specification.md
- docs/notes/tooling.md
Refresh the "Get involved" section of slsa.dev/community:
-   Add links to the SIGs. (I decided against having more detail about the SIGs here because doing so made the page very busy.)
-   Rewrite the intro paragraph to better express how to contribute.
-   Streamline the list of links to be easier to read at a glance. (Compare "Github issues (tracks all work)" to "Leave us an issue on GitHub".)
-   Remove details about meetings, including times and link to OpenSSF calendar, because that info can already be found at the top of the meeting notes doc. This way the meeting notes doc becomes canonical.
-   Fix CSS so that the Goose image takes up less vertical space on desktop and wraps on mobile.
Replace the "Contributors" section with "Governance" on slsa.dev/community. The previous list …
> Update community page; add meeting notes aliases

- docs/_sass/minima/_custom.scss
> Fix rendering of numbered lists

- docs/_sass/minima/_base.scss
I personally find this smooth scrolling very distracting, especially during development.
Things to test:
- Try clicking a link in the table of contents. Previously it would animate the scroll. Now it jumps straight there.
- Go to a particular section of the page then reload. Previously it would jump to the top then animate the scroll, which was distracting. Now it just reloads quickly.
> Disable smooth scrolling

- docs/_sass/minima/_custom.scss
- docs/_sass/minima/_layout.scss
Previously the "draft" banner was on top of the nav menu, which made it impossible to navigate unless you dismissed the banner. We don't actually need a z-index on the banner since it's defined earlier in the document than the rest of the page, but the nav menu needs a z-index to make it appear above the banner.
**Preview:** https://deploy-preview-506--slsa.netlify.app/spec/v1.0/levels
> Layer "draft" banner under the nav menu

- docs/_layouts/post.html
- docs/blog.html
This change adds the label "Guest Post" to the author line of guest blog posts, both to the post itself and the blog page.
> Add label to guest blog posts

- docs/spec/v1.0/levels.md
Signed-off-by: Aaron Bacchi <aaron.bacchi@gmail.com>
Based on this conversation- https://github.com/slsa-framework/slsa/pull/502#discussion_r995886785
My intention for this change is to outline the difference between the weak guarantee in L2 vs the strong guarantee in L3.
I am basing this off of my interpretation of the Authenticated and non-falsifiable requirements today.
Authenticated:
> The provenance’s authenticity and integrity can be verified by the consumer. This SHOULD be through a digital signature from a private key accessible only to the service generating the provenance.
Non-falsifiable: 
> Provenance cannot be falsified by the build service’s users.
> Any secret material used to demonstrate the non-falsifiable nature of the provenance, for example the signing key used to …
> SLSA v1.0 levels - depict differences in authentication L2 vs L3

- docs/spec/v1.0/index.md
The previous content on spec/\*/index.md was redundant with other pages and fell into an awkward middle ground: it was slightly more detailed than the top-level splash page but much less detailed than the individual specification pages. Furthermore, the main thing that people wanted on this page was the table of contents, but that was all the way at the bottom.
Instead of keeping it up-to-date for v1.0, let's drop it entirely. Now the page contains only a table of contents plus a short blurb informing readers about versioning of the spec and the presence of other specifications, which is a common point of confusion.
Note: The `<span>` tags are to used to direct the reader to the version chooser: bottom of page on mobile and right on desktop. You can test this by resizing your window or …
> SLSA v1.0: delete most of index.md

- docs/get-started.md
The [`github-actions-demo`](https://github.com/slsa-framework/github-actions-demo) is old and unmaintained. This PR updates the link to point to the newer and better maintained [`slsa-github-generator`](https://github.com/slsa-framework/slsa-github-generator) repository.
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>
> Change link in getting started

- docs/spec/v1.0/requirements.md
**Preview:** https://deploy-preview-512--slsa.netlify.app/spec/v1.0/requirements
- Rename "L1/2/3" to "Build L1/2/3" and delete "L4".
- Hide the old Source and L4 requirements under a click and identified as "draft" for a future version. This gives an insight into our thinking for the next version, is a hint for readers accustomed to v0.1, and allows us to iterate on the wording over time.
- Move definitions down to where they are used to make the doc easier to read.
Note: no requirements were changed in this PR. Just removing the levels.
This removes one of the "optional" requirements, partially addressing #423.
Part of #510.
> SLSA v1.0: update requirements.md for new tracks

- docs/_sass/minima/_custom.scss
Previously the table-of-contents did not have any visual distinction between two different entries vs one entry with multiple lines - they all ran together.
Now there is slightly more whitespace between entries and slightly less whitespace between lines within an entry.
before | after
--- | ---
> css: distinguish multi-line entries in ToC

- docs/spec/v1.0/levels.md
Reframe the meaning of each level in terms of how much tamper protection they afford, rather than prescribing specific implementation. In concrete terms, this means Build L1 = mistake prevention, L2 = weak tamper protection (fireable offense), L3 = strong tamper protection. This framing seems to resonate well with various parties I've talked to.
In particular, this makes it more clear that reproducible builds or other types of systems can still satisfy SLSA.
Fixes #504.
> SLSA v1.0: frame levels around tamper protection

- docs/get-started.md
Since there is no SLSA 1 GitHub actions provenance generators, on SLSA 1 section we refer to the SLSA 3 generator. This would prevent new users to give up on SLSA 1 if they have builders on Github.
Complements Pull Request #522
Signed-off-by: Diogo Teles Sant'Anna <diogoteles@google.com>
> docs(get-started): add link to provenance generators on SLSA 1 section

- docs/_sass/minima/_base.scss
- docs/spec/v1.0/levels.md
- docs/spec/v1.0/requirements.md
This is an overhaul of the requirements page to:
- #510
- #188
- Simplify the requirements
More specifically:
- Define the implementers: producer, build system, packaging ecosystem, consumer. This should get merged and de-duplicated with Terminology in a future PR.
- Simplify the build levels to minimize the number of independent checkboxes at each level. Now it is expressed in terms of degrees of provenance generation and isolation.
- Move documentation of the provenance to the provenance spec (separate PR). This avoids duplication of documentation and allows readers to see concrete formats. Otherwise we describe it a second time but more abstractly here, which is harder to understand and results in confusion.
This is currently a draft but ready for early review. There are still many …
> SLSA v1.0: overhaul requirements by party.

- docs/_data/nav.yml
- docs/_includes/header.html
- docs/_includes/nav-level.html
- docs/_includes/nav.html
- docs/_sass/minima.scss
- docs/_sass/minima/_layout.scss
- Combine HTML for desktop and mobile menus
- Fix the fact that only one top level item can have a sub menu
- Move "Specifications" -> "Attestations" to a second level sub menu
Please note: While the menu heirarchy is generated dymanically based on the `_nav.yml` contents, the sub menu UI show/hide logic requires the `header.html` `x-data` boolean flags to be in place ahead of time. Hense the hard-coding of these. Adding additional sub-menus in the future will require both `_nav.yml` and `header.html` `x-data` to be updated in a similar manner.
- Increase sub menu width to minimise text wrapping
- Prevent last sub menu item appearing off the screen edge
- Fix main menu width at interim screen sizes (the labels get smushed just before switching to the mobile layout)
- Close sub menus on …
> Main menu updates and fixes

- docs/_data/nav.yml
- docs/spec-stages.md
To address issue #541 this PR adds a page defining the different stages a specification can be in, setting the expectation that every specification being published will display a "Status of this document" section that communicates to the reader what stage of the development the spec is in and what they can expect from it.
> Add definition of specification development stages

- docs/spec/v1.0/index.md
- docs/spec/v1.0/principles.md
The new name better reflects that it is background material rather than an important document that ever reader must read.
Also explain the intent of the page at the top so that readers can quickly determine whether or not to continue reading.
> SLSA v1.0: Rename "Key principles" to "Guiding principles"

- docs/spec/v1.0/requirements.md
The wording from #532 has already been incorporated, so the TODO can be removed.
> SLSA v1.0: Remove obsolete TODO

- docs/_sass/minima/_custom.scss
This was already fixed for ordered lists in #548.
Before: https://slsa.dev/spec/v0.1/requirements#hermetic
After: https://deploy-preview-579--slsa.netlify.app/spec/v0.1/requirements#hermetic
> css: use different symbol for nested lists

- docs/provenance/v1/index.md
This fixes the lint check. Use caps where RFC 2119 is intended and use alternate phrasing where it is not.
> Fix usage of RFC 2119 keywords in provenance v1.

- docs/_includes/versions-dropdown.html
The v1 spec is in a child directory, whereas earlier (0.1 and 0.2) versions are direct children of the provenance folder. This means that when the versions-dropdown replaces the v1 version part with 0.1 or 0.2 in the replacement url includes a trailing '/'. Stripping the trailing url for all items in the version selector fixes navigating between provenance specification versions.
> Fix switching between provenance spec versions

- lint.sh
Previously it always exited with success (0), making it useless as a GitHub Actions presubmit.
Also add comments to explain why we use this structure.
> Fix link.sh to properly set exit code.

- docs/spec/v1.0/requirements.md
This adds a small section indicating that all implementations MUST use industry security best practices.
> Add requirement on using best practices

- docs/spec/v1.0/requirements.md
#515
Signed-off-by: kpk47 <1079282+kpk47@users.noreply.github.com>
> Add SLSA conformance to requirements page

- docs/spec/v1.0/requirements.md
Per issue #601 the v1 spec doesn't make it explicit that provenance metadata should unambiguously identify the output artifact. This minor change makes that more apparent (though perhaps not as explicit as it should be).
> Make the need to identify artifacts more explicit

- docs/_includes/header.html
- docs/_includes/nav-init.liquid
- docs/_includes/nav-level-init.liquid
- docs/_includes/nav-level.html
- docs/_includes/nav.html
x-data must contain the right initializations for the cascading menus to function. This change adds code to generate these initializations automatically based on the menus defined in nav.yaml. This saves us from having to edit both places and to know the internals of how the menus are coded.
Also includes some minor changes to improve the html output.
> Set x-data automatically

- docs/github-actions-workflow/v0.1/index.md
This makes it unambiguous what the `buildType` string should be set to.
> Document the `buildType` string on github-actions-workflow.

- docs/_data/versions.yml
- docs/_includes/versions-dropdown.html
The selector currently offers to switch between versions even when the page does not exist in the other versions, which leads to a 404. This change fixes that by disabling the option if the other version of the page doesn't exist.
To replicate the problem simply go to: https://slsa.dev/spec/v1.0/principles then select "Version 0.1" -> 404
With this fix, the version 0.1 is disabled in the selector.
> Fix version selector

- docs/provenance/v1.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/requirements.md
- Fix broken links from #615, now that the URLs ending in slash no longer resolve.
- Move TODO section from requirements.md to index.md, creating a new "About this release candidate" section.
> SLSA v1.0: Fix broken links; move TODO to new "about this release candidate" section

- docs/github-actions-workflow/examples/v1/example.json
- docs/github-actions-workflow/v1.md
- docs/provenance/v1.md
No one is relying on this string yet, and everything else is v1, so it makes sense to just call it v1. We can rename to v2 if we have a breaking change.
> Rename github-actions-workflow/v0.1 to v1

- docs/_includes/onepage.liquid
- docs/_includes/section.liquid
- docs/spec/v0.1/onepage.md
- docs/spec/v1.0/faq.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/onepage.md
More work can be done on this but with this change one can access the whole SLSA spec on a single page. All the internal links are fixed to be relative to that page, headers are shifted one level done to get the proper TOC.
I primarily focused on the v1.0 version but it also works on the v0.1 version although some headers appear on several pages so when put on the same page it seems a bit odd.
Let me know what you think.
The page is found at /spec/v1.0/onepage and /spec/v0.1/onepage. The version selector even works across! :-)
> Add the SLSA spec as a single page

- docs/github-actions-workflow/v1.md
- docs/provenance/v1.md
Previously there was an inconsistency:
- The "Parsing Rules" said that consumers MUST **ignore** unrecognized fields. The intention is that implementations, or future minor versions of the spec, can add extra fields without invalidating what's already there.
- However, the design of `externalParameters` and the corresponding verification instructions assumed that consumers would **reject** unrecognized parameters. The idea here is that an unrecognized parameter cannot be expected, thus it's err on the side of safety an reject.
This PR attempts to fix this issue by stating that consumers MUST ignore unrecognized fields **unless otherwise noted** and noting that `externalParameters` is such an exception.
Is this sufficient to resolve the issue? Are there still any concerns about confusion …
> Provenance v1: Clarify when to ignore unrecognized fields

- docs/_data/versions.yml
- docs/github-actions-workflow/index.md
- docs/github-actions-workflow/v1.md
- Add redirect to v1 if version is unspecified.
- Fix version.yml to include this version. This has the effect of re-adding the "draft" banner.
- Fix typo in reference to `externalParameters`.
> Fixes for github-actions-workflow.

- docs/provenance/v1.md
- Make `builder.id` required, which is how it was in v0.2. (Before this commit, v1 said that the `id` MAY be implicit from the signer's identity.)
- Replace uses of `builder` with `builder.id`. The latter is the identity, while the former includes more information about the builder.
- Remove TODOs about `id` being optional.
Fixes #622.
> Provenance v1: make `builder.id` required again

- docs/_posts/2023-02-24-slsa-v1-rc.md
The blog post is missing one crucial piece of info: a link to the spec!
It does link to various parts of it but not the spec directly. This PR fixes that.
> Add missing link to the spec

- docs/github-actions-workflow/v1.0.md
- docs/provenance/v1.0.md
- docs/spec/v1.md
I keep mistyping `/spec/v1` when it's really `/spec/v1.0` and similarly `/provenance/v1.0` when it's really `/provenance/v1`. This commit creates simple redirects to jump to the right one.
> Redirect between "v1" and "v1.0"

- docs/provenance/v1.md
Commit f96aac7a made `builder.id` a required field but forgot to update the example root of trust accordingly.
> provenance v1: use non-empty builderId in example

- docs/verification_summary/v1.0.md
- docs/verification_summary/v1.md
Copied from v0.2.md
* materials -> resolvedDependencies
* Relax SlsaResult to allow other fields
Can update to use ResourceDescriptor or AritfactReference if/when desired.
fixes #663
> Create v1 of verification summaries

- docs/_includes/pagination.html
- docs/_layouts/default.html
- docs/_layouts/specifications.html
- docs/_layouts/standard.html
- docs/spec/v0.1/faq.md
- docs/spec/v0.1/index.md
- docs/spec/v0.1/levels.md
- docs/spec/v0.1/requirements.md
- docs/spec/v0.1/terminology.md
- docs/spec/v0.1/threats.md
- docs/spec/v1.0-rc1/faq.md
- docs/spec/v1.0-rc1/future-directions.md
- docs/spec/v1.0-rc1/index.md
- docs/spec/v1.0-rc1/levels.md
- docs/spec/v1.0-rc1/principles.md
- docs/spec/v1.0-rc1/requirements.md
- docs/spec/v1.0-rc1/terminology.md
- docs/spec/v1.0-rc1/threats.md
- docs/spec/v1.0-rc1/verifying-systems.md
- docs/spec/v1.0/faq.md
- docs/spec/v1.0/future-directions.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/levels.md
- docs/spec/v1.0/principles.md
- docs/spec/v1.0/requirements.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.0/threats.md
- docs/spec/v1.0/verifying-systems.md
- docs/spec/v1.0/whats-new.md
- Added `prev_page` and `next_page` config to each spec page `.md` file (across all versions)
- Added logic to output links in `standard`, `default` and `specifications` layout templates
- This has been done in a more manual/hardcoded way to ensure the flexibility needed to name/link to all spec pages. It could technically be done using Jeykell "Collections" and a more dynamic implimentation, but doing so would mean a larger rework of the folder structure and would be impacted by the current method of versioning. This hardcoded method seemed the safer option in the short term
- We have taken the order of pages in versions `1.0` and `1.0-rc1` from that shown in their respective `onepage` templates
- Both `1.0` and `1.0-rc1` specs have pages in their directories which don't appear in the …
> Add spec level previous and next links (all versions)

- docs/_sass/minima/_custom.scss
- docs/attestation-model.md
- docs/spec/v0.1/levels.md
- docs/spec/v0.1/requirements.md
- docs/spec/v0.1/terminology.md
- docs/spec/v0.1/threats.md
- docs/spec/v1.0-rc1/index.md
- docs/spec/v1.0-rc1/levels.md
- docs/spec/v1.0-rc1/principles.md
- docs/spec/v1.0-rc1/requirements.md
- docs/spec/v1.0-rc1/terminology.md
- docs/spec/v1.0-rc1/threats.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/levels.md
- docs/spec/v1.0/principles.md
- docs/spec/v1.0/requirements.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.0/threats.md
Previously, many pages started with a `<div class="subtitle">` that rendered the first paragraph in larger font, to give an overview of the page. But this was not used consistently since some pages forgot the tag.
Now the first paragraph is always rendered larger (using CSS selectors) without need for the tag. This makes the source easier to maintain and also makes the site more consistent.
> Automatically render first paragraph as "subtitle"

- docs/github-actions-workflow/examples/v1/example.json
- docs/provenance/schema/v1/provenance.cue
- docs/provenance/v1.md
In in-toto Statement v1, a new `gitCommit` algorithm was added as a more specific algorithm instead of `sha1`. Use this in our provenance format and examples.
Also add missing `_type` field to the example provenance file.
> Use `gitCommit` instead of `sha1` in provenance

- docs/_includes/pagination.html
- docs/spec/v0.1/faq.md
- docs/spec/v0.1/index.md
- docs/spec/v0.1/levels.md
- docs/spec/v0.1/requirements.md
- docs/spec/v0.1/terminology.md
- docs/spec/v0.1/threats.md
- docs/spec/v1.0/faq.md
- docs/spec/v1.0/future-directions.md
- docs/spec/v1.0/levels.md
- docs/spec/v1.0/onepage.md
- docs/spec/v1.0/principles.md
- docs/spec/v1.0/requirements.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.0/threats-overview.md
- docs/spec/v1.0/threats.md
- docs/spec/v1.0/verifying-artifacts.md
- docs/spec/v1.0/verifying-systems.md
- docs/spec/v1.0/whats-new.md
With this change the titles of the pages used in the prev/next pagination links are retrieved directly from the pages themselves so that they don't need to be repeated in the front matter, eliminating a source of error and simplifying maintenance.
It also fixes a few broken pagination links and onepage v1.0 (although not completely).
> Fix pagination

- docs/provenance/v1.md
Add a recommendation for the `builder.id` URI to resolve to documentation that explains the scope, level, and accuracy of the builder.
Fixes #594.
> Provenance v1: builder.id should explain itself

- docs/provenance/v1.md
This follows #707 which did the same for GitHub Actions.
Fixes #662.
> Add link to GCB definition

- docs/spec/v1.0/terminology.md
I meant to remove this in #664 but messed up the merge in 6605135.
Thanks @di for pointing this out!
> Remove stale TODO from terminology page

- docs/spec/v1.0/requirements.md
- docs/spec/v1.0/threats.md
In order to help reduce confusion around ephemeral and isolated properties, these have been merged into a single isolated property. Additional clarity is added to the isolated build requirement, relating it to the previous hermetic requirement.
Relates to #657
Fixes #291 by being more specific around build caches.
Fixes #321 and addresses comments about self-hosted GitHub runners
Some content taken from https://github.com/slsa-framework/slsa/pull/685#discussion_r1140522178 by @MarkLodato.
> Combine ephemeral and isolated to isolated

- docs/_includes/header.html
Most readers probably don't want to be taken to the latest approved version, but they might want to select a release candidate (or even know that a release candidate exists). So refer them to the version selector rather than adding a link.
Also display what version it is a draft of, to make it more clear to readers.
I'm thinking that when we send out a call to review v1.0, the current banner would be confusing to people.
> Make the draft banner more useful.

- docs/provenance/v1.md
Updates the SLSA Provenance parsing rules for extension fields to match the latest parsing guidelines from the in-toto Attestation Framework. In particular, the new rules remove the recommendation to use TypeURIs and add an explanation to avoid certain special characters in extension field names.
Fixes #670
> Update parsing rules to match latest in-toto extension field rules

- docs/_includes/head.html
- docs/spec/v0.1/onepage.md
- docs/spec/v1.0-rc1/onepage.md
- docs/spec/v1.0/onepage.md
These pages duplicate content found elsewhere on the site, which is generally discouraged by search engines. Since they combine multiple pages, we can't provide a single canonical link, and because these are likely not the pages we want to show up in search results, just mark these as `noindex` instead.
> Set `noindex` on 'onepage' pages

- docs/verification_summary/v1.md
- Use ResourceDescriptor instead of re-defining the object with a uri and digest type. This brings VSA to be consistent with Provenance.
- Update `_type` to use Statement/v1.
- Fix broken links to point to v1.
No meaningful changes were intended.
/cc @AdamZWu
> VSA v1: update to in-toto attestation v1

- docs/verification_summary/v1.md
Our parsing rules say that we should not differentiate between a set-but-empty field and an unset field, but `inputAttestations` violated this rule.
Since we do not have a use case for distinguishing between these two cases, just merge them together in the spec.
Fixes #753.
> VSA v1: remove difference between empty and unset

- docs/spec/v1.0/levels.md
I commented that differentiation between the levels wasn't intuitive in https://github.com/slsa-framework/slsa/pull/750/files#r1150745321. I think that if I just modify it to explicitly state that this is the basic provenance that it becomes clearer.
> Clarify level differentiation

- docs/spec/v1.0-rc1/threats.md
- docs/spec/v1.0-rc1/verifying-artifacts.md
- docs/spec/v1.0/threats.md
- docs/spec/v1.0/verifying-artifacts.md
This addresses Issue #747.
I'm really not sure why Jekyll doesn't like the link in threats.md but for some reason in this instance linking to the .md file with a fragment identifier fails because the .md remains in the generate html page...
@kpk47 I only found one instance of a link to the certification/conformance page.
> Fix some broken links

- docs/_includes/nav-level.html
- docs/_sass/minima/_custom.scss
Previously all nav bar text entries were rendered identically, whether or not it was clickable. (Section titles are not clickable.) This made it a little hard to read.
Now (non-clickable) section titles are rendered differently from (clickable) links. The new color is light green, the same color as the prior hover text. This seems like a decent compromise to me. I experimented with bold, small caps, and others, but a slight change in color seemed the most subtle and useful.
To make this distinct from hover, hover/focus is now rendered the same as on the main page: with an underline rather than a change of color.
**For reviewers:** Do you think this is better?
In the screenshots below, "About SLSA" is the current page and the mouse is over "Verifying build systems" (i.e. hover/focus). …
> Color nav bar section titles differently from links

- docs/spec-stages.md
This change clarifies when/why SLSA will increment its version number and how users should refer to SLSA levels in context where the version number matters.
Fixes #570
> Describe SLSA's versioning conventions.

- docs/spec/v1.0/index.md
Also the spec now encompasses both the levels and the formats, so remove that part as well.
> Remove obsolete reference to version selector.

- docs/spec/v1.0/requirements.md
In SLSA v0.1 we had said that the provenance MUST identify the package by cryptographic digest, but this was implicit in v1.0 from "unambiguously identifies the output package" and "equivalent information as SLSA Provenance". Still, there is room for misinterpretation, so this change calls out identifying the output artifact by cryptographic digest so there is no room for misinterpretation.
Also splits the paragraphs to be more readable.
Fixes #601.
> Explicitly mention identifying package by digest

- .github/CODEOWNERS
Adds myself as a reviewer for all current and future `distributing-provenance.md` pages.
> Add @di to CODEOWNERS as reviewer

- docs/attestation-model.md
This closes out the TODO on the Attestation Model page.
I chose these algorithms because we recommend SHA-256 elsewhere in the spec and ECDSA over P-256 has the same security strength. I'm open to other suggestions.
> Add recommended crypto algorithms for DSSE.

- docs/spec/v1.0/terminology.md
We use the roles "producer," "consumer," and "infrastructure provider" in the spec but don't define them.
I also defined "verifier" since we use that sometimes, but it's less common than the others.
#783
> Add a roles section to terminology.md.

- docs/attestation-model.md
PR to explain attestations in a series of documentation updates outlined in Issue #672.
Adds a section telling users how to choose among attestations formats based on whether they are using SLSA for first party, open source, or third party close source code.
@MarkLodato @kpk47 @arewm @lehors
> Explain attestation formats

- docs/spec/v1.0/verifying-artifacts.md
- Fix references to threats D and E, whose labels have swapped.
- Use relative links instead of absolute.
> Fix references to threats on verifying-systems.md

- docs/_data/nav/v1.0-rc1.yml
Previously it pointed to v1.0-rc1 which does not exist
> Fix links to v1-rc1 provenance

- docs/spec/v1.0/verifying-artifacts.md
The fields `buildType` and `externalParameters` start with a lowercase letter.
> v1: fix field name typos in verifying-artifacts.md

- docs/notes/tooling.md
The tooling group switched to a different notes document when they lost access to the prior one. Update the redirect to point to the active notes document.
> Update redirect for tooling notes

- docs/spec/v1.0/distributing-provenance.md
- docs/spec/v1.0/verifying-artifacts.md
As discussed at the 2023-04-03 Specification Meeting, we agreed to downgrade the requirements (MUST) in "verifying artifacts" and "distributing provenance" to be recommendations (SHOULD) since we have not yet sufficiently defined what a "SLSA-conformant system" means. Hopefully we can address this in a future revision of the specification.
This leaves one use of "MUST", namely "Producers MUST publish attestations in at least one place", because that is a requirement from "producing artifacts".
Fixes #786.
> Avoid MUST in "verifying artifacts" and "distributing provenance"

- docs/spec/v1.0/about.md
Previously the "Who is SLSA for? / Software producers" bullet described producers as individuals rather than organizations, and said "insider risk and tampering" as though they were distinct threats. Similarly, the "What SLSA doesn't cover / Developer trust" bullet talked about the threat of individuals writing malicious code, which seems to be exactly the kind of "insider risk and tampering" threat described above.
This change fixes that by distinguishing between individuals and organizations. SLSA addresses the threat of individuals subverting the organization's goals, but does not address the organization having bad goals.
Addresses most of #805. There are still pending discussion around "insider" and "producer trust."
> Clarify insider threats on "About SLSA"

- docs/_sass/minima.scss
- docs/_sass/minima/_custom.scss
When loading a link to a section within the page:
- Add enough scroll margin at the top to ensure that the header does not hide the target of the link.
- Briefly highlight the target of the link with a subtle background color to make it more clear what was actually clicked on.
Known limitations:
- Visually the highlight would look nicer the `line-height` of `h2` and family were about 1.6 (right now `h2` is 1 and `h3` and up are 1.3) but changing that would require some adjusting of other margins which I don't feel like doing right now.
- This doesn't fix the "draft" banner from being drawn over the link target. Fixing that would require either always setting a larger scroll margin (which would be too big once the banner is dismissed) or some more complicated solution. What is in this …
> css: improve look of :target element

- docs/provenance/v1.md
The last TODO or RFC comment was asking about adding a "tenant" field. I had anticipated sending out a PR to add such a field before RC2 but I didn't get it out in time. Let's remove the RFC since we're no longer asking for comments on this. Users who want this can file an issue.
> Remove final "RFC" comment in provenance.md

- docs/provenance/schema/v1/provenance.cue
- docs/provenance/schema/v1/provenance.proto
- docs/provenance/v1.md
Action item from community meeting 4/10/2023 - fixes #815
I specifically left the RC1 and RC2 files alone and only updated the "v1" files- please let me know if you think that is wrong and we can correct that.
> Provenance v1: rename `systemParameters` to `internalParameters`

- docs/spec/v1.0/whats-new.md
This is an expanded and updated version of the v1.0 RC blog post.
A nice future step would be to write a detailed list of changes as an additional second section, similar to the change history of the provenance and VSA pages.
Fixes #592.
> Add What's New in v1.0 page

- docs/spec/v1.0/future-directions.md
This change was proposed in the SLSA Specification meeting on April 10, 2023 from a discussion on issue #802.
Secure build systems are essential for building secure artifacts. While the work leading up to the 1.0 release for the SLSA build track was not able to come to concensus around verifying build systems, there is potential for a future track that addresses build system concerns.
There is an opportunity for concerns to be met for those building and operating build systems, those checking conformance of those systems, and end-user of those systems. Each has their own needs.
Fixes #802
cc @MarkLodato
> Add section on Build Platform Operations track to future directions

- docs/_includes/header.html
- docs/_sass/minima/_custom.scss
This is a follow-on to 9492b35 (#811).
When loading a link to a section within the page, add enough scroll padding to prevent the header from overlapping with the target.
While 9492b35 set the `scroll-padding-top` of `<html>` statically, this change sets the `scroll-margin-top` of all clickable elements dynamically based on whether or not the banner is visible. It's not possible to dynamically set the style of `<html>` based on the state of a checkbox (inside the `<html>`) since there is no CSS parent selector.
Preview: https://deploy-preview-822--slsa.netlify.app/spec/v1.0/requirements#provenance-unforgeable
In the following screenshot, the "Provenance is Unforgeable" link was clicked:
| Description | Screenshot |
| --- | --- |
| Before | …
> css: prevent "draft" banner from occluding :target

- docs/_config.yml
- docs/_includes/header.html
- docs/index.md
- docs/levels.md
- docs/provenance/v0.1.md
- docs/provenance/v0.2.md
- docs/requirements.md
- docs/spec/index.md
- docs/spec/v0.1/index.md
- docs/terminology.md
- docs/threats.md
- docs/use-cases.md
This was intended to be an easy-to-use configuration parameter to point to the latest version of the spec, but in practice it was not actually helpful. In practice all of the pages have change between versions, so it's not helpful to have such a variable.
- It is only actually used in two places, neither of which are valuable:
- The top-level index: this tried to point dynamically at the latest version but that won't work because all of the pages have changed between versions. We really do need to hard-code it here.
- Provenance v0.1 and v0.2: we have since decided to tie the provenance and spec versions together, so these ought to be hard-coded to v0.1.
- All other uses are either comments or dead code. (The dead code is also removed in this commit.)
Part of #513.
> Remove current_spec_version and unused code

- docs/_data/versions.yml
- docs/_includes/status.html
This configuration setting is not used anywhere. Remove it for code health.
(The configuration for what shows the default left-hand nav menu is controlled by 
Part of #513.
Note: The default version for the left-hand nav menu is configured in [`data.nav.config.url_to_key.latest`](https://github.com/slsa-framework/slsa/blob/f7b23441fc6394a9062c69b149fbe236972a747f/docs/_data/nav/config.yml#L11), which is used as the default in [_includes/nav.html](https://github.com/slsa-framework/slsa/blob/f7b23441fc6394a9062c69b149fbe236972a747f/docs/_includes/nav.html#L10-L13).
> Remove unused `current` version setting

- docs/provenance/index.html
- docs/provenance/v0.2-draft.html
- docs/verification_summary/index.html
There are already Markdown files that do the redirect. The html files are redundant.
Part of #513.
To test, the following two URLs should still redirect to /v0.2 as before:
- https://deploy-preview-831--slsa.netlify.app/provenance/
- https://deploy-preview-831--slsa.netlify.app/provenance/v0.2-draft
- https://deploy-preview-831--slsa.netlify.app/verification_summary/
> Remove unused html redirect files

- docs/_sass/minima/_custom.scss
Previously the nav bar did not have any visual distinction between two different entries vs one entry with multiple lines - they all ran together.
Now there is slightly more whitespace between entries and slightly less whitespace between lines within an entry, with all other spacing being *almost* pixel equivalent.
Note: 0fa8c9d did this for the TOC, without being as careful about pixel equivalence.
To preview, compare "Verifying build platforms" and "For infrastructure providers" in the screenshots below, or flip back and forth between the netlify [preview](https://deploy-preview-840--slsa.netlify.app/spec/v1.0/) and the [live site](https://slsa.dev/spec/v1.0/).
| Before | After |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/58860/232084256-ad955dd0-4b69-4645-af9b-9 …
> css: distinguish multi-line entries in nav bar

- docs/provenance/v1-rc1.md
- docs/provenance/v1-rc2.md
- docs/provenance/v1.md
Previously it was not obvious what the changes were between RC1, RC2, and final. Now readers who are interested can see the specific section. Also call out the rename in v1-rc1 and v1-rc2 documentation, since some readers may get caught off-guard.
The current design shows all changes from the previous stable release (v0.2), then repeats the changes since RC1 and RC2. Most readers likely care about the former, so making the RC1/RC2 differences less prominent seems worthwhile. An alternative is to list RC1 and RC2 in the change history, but that is probably a loss of readability for most readers.
> Provenance: raise visibility of changes since RCs

- docs/spec/v1.0/threats-overview.md
- docs/spec/v1.0/threats.md
- docs/spec/v1.0/verifying-artifacts.md
The diagram assumes familiarity with the SLSA supply chain model. Remind the reader that the Terminology page explains the components of the diagram.
Fixes #844.
> Link to Terminology beneath each supply chain diagram

- docs/_data/versions.yml
- docs/provenance/schema/v1/provenance.cue
- docs/provenance/v1.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/verifying-artifacts.md
- Mark SLSA v1.0, Provenance v1, and VSA v1 as Approved.
- Mark release candidates as Retired and hide them from the dropdown.
- Remove `?draft` from `predicateType`.
Part of #513.
**Important:** We cannot merge this until Tuesday, April 18, which is after the end of the mandatory [two-week review period](https://github.com/slsa-framework/governance/blob/main/5._Governance.md#4-specification-development-process). In the meantime, please review and approve so that we can merge on the 18th.
**Note:** This just marks v1.0 as approved. PR #832 sets the default version to v1.0.
> SLSA v1: Mark as Approved specification

- docs/_data/nav/config.yml
- docs/community.md
- docs/faq.md
- docs/index.md
- docs/levels.md
- docs/provenance/index.md
- docs/requirements.md
- docs/spec/faq.md
- docs/spec/index.md
- docs/terminology.md
- docs/threats.md
- docs/use-cases.md
- docs/verification_summary/index.md
- Make v1.0 the default nav version.
- Update front page to link to v1.0.
- Update redirects to point to v1.0.
- Update "project status" on index and community to say that v1.0 is stable.
Part of #513.
**Imprortant:** We will not merge this until after #829 (on Tuesday, April 18).
**Note:** This just sets the default version to v1.0. PR #829 marks it as Approved.
> SLSA v1: make v1.0 the default version

- docs/_posts/2023-05-02-in-toto-and-slsa.md
@TomHennen and I worked on this post (with help from the in-toto Attestation Framework maintainers, @mlieberman85, etc.) that discusses in-toto's role in SLSA and the work we're doing / have planned that can tie back to future SLSA tracks.
> Add blog post about in-toto and SLSA

- docs/_data/versions.yml
- docs/_includes/header.html
- docs/provenance/v0.1.md
- docs/provenance/v0.2.md
- docs/verification_summary/v0.1.md
- docs/verification_summary/v0.2.md
When viewing older versions of the spec, this PR adds a notice at the top of pages linking them to the corresponding page in the newest version of the spec (or the top page if the page doesn't exist).
Also removes older "Note about 0.x versions" which referenced v1.0 before it was released. Removed because notices at the top of the page should supersede them.
> feat: Add notice if viewing outdated versions of the spec

- docs/spec/v0.1/faq.md
- docs/spec/v1.0-rc1/faq.md
- docs/spec/v1.0-rc2/faq.md
- docs/spec/v1.0/faq.md
I think [this section](https://google.github.io/building-secure-and-reliable-systems/raw/ch14.html#hermeticcomma_reproduciblecomma_or_veri) is the right one. 
Both old [benefits](https://static.googleusercontent.com/media/sre.google/en//static/pdf/building_secure_and_reliable_systems.pdf#page=357) and [Hermetic, Reproducible, or Verifiable?](https://sre.google/static/pdf/building_secure_and_reliable_systems.pdf#page=357) don't work any more.
> Fixes bad permalinks for building-secure-and-reliable-systems on the FAQ pages

- .github/workflows/deploy_website.yml
In #871 we removed the `environment` specification from the `deploy` job during code review (at [my querying](https://github.com/slsa-framework/slsa/pull/871#discussion_r1214218701)), but it turns out it _is_ required to set the environment (even if the docs for the action don't make that 100% clear).
This PR re-introduces the environment configuration for the deploy job. In addition, it moves the permissions required for the deploy job to that job (PLP).
> Fix new deploy website action

- .gitignore
- README.md
- docs/_config.yml
- docs/_redirects
Now `https://slsa.dev/gh[/...]` is an easier-to-type alias for `https://github.com/slsa-framework/slsa[/...]`.
This is the first PR that sets up Netlify redirects. Future PRs will update our existing redirects to use this new framework.
Can be tested through deploy previews or through the Netlify CLI. (Future PR will update our dev documentation.)
Previews:
* https://deploy-preview-893--slsa.netlify.app/gh
* https://deploy-preview-893--slsa.netlify.app/gh/issues
* https://deploy-preview-893--slsa.netlify.app/gh/pulls
> impl: add convenience `/gh` redirect to our GitHub repo

- docs/how-to-infra.md
The "How to SLSA for implementers" page headings should nest, so that the "Package registry" and "Compiler or other ..." headings are beneat the "Types of infrastructure" heading. This change re-balances headings to match.
> style: fix heading levels on how-to-infra

- docs/spec/v0.1/threats.md
- docs/spec/v1.0-rc1/threats.md
- docs/spec/v1.0-rc2/threats.md
- docs/spec/v1.0/threats.md
Each version of the threats page features a typo in an example where provenance is spelled provence, this change fixes each instance of the typo.
> spec-editorial: fix provence->provenance typo in threats

- relatedwork.md
The reference links for "Threats, Risks, and Mitigations in the Open Source Ecosystem" and
"Binary Authorization for Borg" were missing.
> impl: add missing links in relatedwork doc

- renovate.json
Update the renovate configuration so that patches and PRs from renovate follow the project's conventional commit guidelines.
Fixes: #910 
Signed-off-by: Joshua Lock <joshua.lock@uk.verizon.com>
> impl: update renovate config for conventional commits

- docs/notes/index.md
Update the list of meeting notes on slsa.dev/notes to no longer say
"bi-weekly".
> nonspec: community meeting is no longer biweekly

- .github/workflows/enforce-tags.yml
The action's documentation says that only these three events are needed.
Without that, the action is called unnecessarily.
> impl: only call enforce-tags on relevant events

- CONTRIBUTING.md
Apply some minor editorial changes to improve readability without
changing the meaning:
- Split out "pull request conventions" into a separate section, since it
was a bit buried in "review and approval." The former is what the user
does before the PR is sent, while the latter is what to expect after
it is sent.
- Remind the reader in the "pull request conventions" that every commit
needs to be signed off but otherwise does not matter due to
squash-and-merge. This was easy to miss before.
- Explain that the table is in order of precedence and that a maintainer
will update the tag if needed.
- Apply various wording improvements.
This PR is hard to review as a whole since it moves AND edits the same hunk. I recommend viewing each commit individually. The first commit just moves the text …
> impl: improve readability of CONTRIBUTING

- docs/_layouts/redirect.html
- docs/_redirects
- docs/faq.md
- docs/getinvolved.md
- docs/github-actions-workflow/index.md
- docs/github-actions-workflow/v1-rc1.md
- docs/github-actions-workflow/v1.0.md
- docs/github-actions-workflow/v1.md
- docs/levels.md
- docs/notes/community.md
- docs/notes/positioning.md
- docs/notes/spec.md
- docs/notes/specification.md
- docs/notes/tooling.md
- docs/provenance/index.md
- docs/provenance/v0.2-draft.md
- docs/provenance/v1.0.md
- docs/requirements.md
- docs/spec/faq.md
- docs/spec/index.md
- docs/spec/v1.md
- docs/terminology.md
- docs/threats.md
- docs/use-cases.md
- docs/verification_summary/index.md
- docs/verification_summary/v1.0.md
Switch to Netlify's HTTP-level redirects instead of HTML-level
`<meta refresh>` redirects. (Historical note: we originally used the
latter because GitHub Pages did not support HTTP-level redirects.)
Advantages:
- Preserves URL fragments.
Example: slsa.dev/levels#build-l3 no longer drops the `#build-l3`.
- Supports directory redirection path components after the redirect.
Example: slsa.dev/spec/v1/levels now works.
- Supports temporary redirects (302). The problem with `<meta refresh>`
is that they are always interpreted as permanent, which is a problem
when we do a version bump (e.g. /levels -> /spec/v1.0/levels).
- Cleans up our directory tree, which now only contains true content.
> impl: use Netlify redirects instead of HTML

- docs/_redirects
This was accidentally dropped from 46673cf.
> impl: fix broken redirect of /requirements

- docs/github-actions-workflow/README.md
The README is obsolete as of 46673cf, which replaced `.md` redirects
with the central `_redirects` file.
> impl: remove obsolete README for GHA buildtype

- .github/workflows/enforce-tags.yml
- CONTRIBUTING.md
Add a new `blog` tag for pull request titles since they are distinct
from official non-spec documentation.
> impl: add "blog" PR tag, fix typos

- docs/_posts/2023-05-02-in-toto-and-slsa.md
- docs/attestation-model.md
Fixing a broken link.
Broken link: https://github.com/in-toto/attestation/blob/main/spec/v1.0/bundle.md
Fixed link: https://github.com/in-toto/attestation/blob/main/spec/v1/bundle.md
> impl: fix broken link to in-toto

- docs/provenance/v0.1.md
- docs/provenance/v0.2.md
- docs/provenance/v1-rc1.md
- docs/provenance/v1-rc2.md
- docs/provenance/v1.md
- docs/verification_summary/v0.1.md
- docs/verification_summary/v0.2.md
- docs/verification_summary/v1-rc2.md
- docs/verification_summary/v1.md
In the top of the Provenance and VSA specification pages, explicitly
state the `predicateType` and instruct the reader to use this string
rather than the URL. Also move the link to in-toto and the RFC 2119
blurb (if present) up there as well.
Motivation:
1. Remove ambiguity, particularly around trailing slashes.
2. Open the path to move provenance and VSA underneath the spec
directory, so that everything is versioned together. If that happens,
we'll redirect the `predicateType` URI to the latest minor version.
> editorial: state `predicateType` explicitly

- docs/spec/v1.0-rc2/threats.md
- docs/spec/v1.0/threats.md
The v1.0 and v1.0-rc2 versions of the page have the same typo: "protects agains"
Signed-off-by: Joshua Lock <joshuagloe@gmail.com>
> editorial: fix typo on threats and mitigations page

- .github/workflows/enforce-tags.yml
- CONTRIBUTING.md
Add a new `fix` PR tag for typos, broken links, and similar. Previously
these were categorized as `editorial`, but that sounded too
significant and required two maintainers to approve plus 24 hours wait.
The new `fix` category is treated the same as `impl`, requiring only one
approval and no wait time.
Also:
- Add a paragraph explaining the purpose of the PR tag.
- Rephrase the preface to the table to provide more clear instructions.
- Create a section heading for the table now that the size of the
section has grown.
> impl: add `fix` PR tag and explain purpose of tags

- docs/spec/v1.1/index.md
- docs/spec/v1.1/onepage.md
- docs/spec/v1.1/provenance.md
Fix the v1.1 spec's index, onepage and provenance to link to the v1.1 versions of content.
Signed-off-by: Joshua Lock <joshua.lock@uk.verizon.com>
> editorial: fix some v1.1 links

- .github/workflows/conventional-commits.yml
- CONTRIBUTING.md
In CONTRIBUTING, switch to terminology that is consistent with GitHub
and Conventional Commits / action-semantic-pull-request:
Before:
<tag>: <title>
<description>
After:
<type>: <subject>
<body>
The whole first line is called the "PR title" (unchanged). Previously
this same term was ambiguously also used for what is now `<subject>`.
Note: Conventional Commits and action-semantic-pull-request disagree on
`<subject>`, with Conventional Commits calling it `<description>`. The
name `<subject>` seems less likely for confusion, so we prefer that one.
> impl: use conventional names for parts of a PR

- CONTRIBUTING.md
As discussed in the conversation for PR #892, specifically:
https://github.com/slsa-framework/slsa/pull/892#issuecomment-1628787792
we should treat the "What's New" page as a Changelog and require
that all content changes to the specification have a corresponding
entry. Update "Contributing to SLSA" to capture this requirement.
> impl: require a changelog entry for content changes

- CONTRIBUTING.md
As discussed at the 2023-08-21 specification meeting, we do not want to
require a 72h waiting period + 3 reviewers for changes to Draft
specifications, since that will make the iteration speed painfully slow.
Draft specifications are clearly marked as unapproved, and there is
still a Candidate approval process to review the whole spec. Therefore,
change CONTRIBUTING to note that Draft versions are manager discretion
regarding waiting period and number of reviewers.
Fixes #953.
> impl: relax review requirements during Draft stage

- docs/_redirects
fixes link [hypothetical curl example](https://slsa.dev/example.md) to example.md at https://slsa.dev/spec/v1.0/use-cases#motivating-example
> fix: add redirect for removed example.md

- docs/spec/v0.1/provenance.md
- docs/spec/v0.1/threats.md
- docs/spec/v0.2/provenance.md
- docs/spec/v1.0-rc1/requirements.md
- docs/spec/v1.0-rc2/principles.md
- docs/spec/v1.0-rc2/requirements.md
- docs/spec/v1.0-rc2/threats.md
- docs/spec/v1.0/faq.md
- docs/spec/v1.0/requirements.md
- docs/spec/v1.0/threats.md
- docs/spec/v1.1/faq.md
- docs/spec/v1.1/requirements.md
- docs/spec/v1.1/threats.md
I found some typos when reading https://slsa.dev/spec/v1.0/requirements and used github.com/client9/misspell/cmd/misspell to fix various others.
> fix: fix various typos in specification files

- docs/spec/v1.0-rc2/verifying-artifacts.md
- docs/spec/v1.0/verifying-artifacts.md
- docs/spec/v1.1/verifying-artifacts.md
The "processing model" part of the in-toto attestation specification has
been renamed and  moved to a new "validation model" page. Update the
references to the processing model in our "verifying artifacts" page to
link to the validation model instead.
> fix: in-toto attestation "processing model" moved

- CONTRIBUTING.md
- README.md
As discussed in the 2023-10-09 specification meeting, create a new
"Project lifecycle" for major projects (new version, new track, etc).
The main idea is to assign a "project shepherd" to oversee the project.
This person is responsible for moving the project along. The reason for
creating this is that many projects seem to stagnate without a single
responsible person.
This commit populates the initial list of projects as per our discussion
at the meeting.
> impl: Create new project lifecycle process

- docs/spec/v1.0/levels.md
Update levels.md to align with requirements.md and to make it more clear how the requirements on the build platform differ between levels:
Build L1:
- Problem: levels.md incorrectly implied that that the *platform* must generate the provenance.
- Fix: Update levels.md to say that provenance must simply "exist", matching the wording on requirements.md. Also simplify the wording while we're at it.
Build L2:
- Problem: The phrase "ensures the trustworthiness of the provenance" could be misread as being a general requirement for L2 builds, whereas the intention was just as a qualifier on "some equivalent platform." Also, the intent of the build platform generating and signing the provenance was unclear, further exacerbating the problem above.
- Fix: Simplify this bullet to focus on the intent …
> editorial: clarify build platform reqs in levels.md

- CONTRIBUTING.md
- README.md
As pointed out in #981, the term "project" is used for SLSA overall. For
example, see the top of CONTRIBUTING.md. To avoid overloading that term,
rename to "workstream". This seems to imply the same concept.
> impl: rename "project" to "workstream"

- docs/_data/nav/v0.1.yml
- docs/_data/nav/v0.2.yml
- docs/_data/nav/v1.0-rc1.yml
- docs/_data/nav/v1.0-rc2.yml
- docs/_data/nav/v1.0.yml
- docs/_data/nav/v1.1.yml
- docs/spec/v0.1/verification_summary.md
- docs/spec/v0.2/verification_summary.md
- docs/spec/v1.0-rc2/verification_summary.md
- docs/spec/v1.0/verification_summary.md
- docs/spec/v1.1/verification_summary.md
- Expand VSA --> Verification Summary in the left-hand nav menu. The VSA acronym only makes sense to readers familiar with the VSA.
- Remove redundant "SLSA" prefix from VSA page titles
- Remove specification version from VSA page descriptions
> editorial: tweak presentation of VSA pages

- docs/spec/v1.1/principles.md
Document the principles around defining new levels and tracks. As we
expand SLSA, we need to ensure that SLSA remains focused and
understandable. A large part of that is having a consistent and simple
philosophy.
> content: add principle for defining levels/tracks

- docs/spec/v1.1/verification_summary.md
- docs/spec/v1.1/whats-new.md
Recommended that the `digest` field of `ResourceDescriptor` is set in a Verification Summary Attestation's (VSA) `policy` object.
Fixes: #803
> content: recommend a VSA include the policy's digest

- .github/CODEOWNERS
- MAINTAINERS.md
This change publishes the current list of maintainers in MAINTAINERS.md. It also deletes .github/CODEOWNERS since we were using it to track maintainers previously.
#997
> impl: Create MAINTAINERS.md

- docs/spec/v1.0/verification_summary.md
- docs/spec/v1.1/verification_summary.md
This is related to issues #968, just a cleanup preparing the proposal to remove "FAILED" at v1.1 in a future commit.
> editorial: Clarify DependencyLevels, SlsaResult, and quote level keys.

- docs/spec/v1.0/faq.md
- docs/spec/v1.1/faq.md
Resolves: #966
Some CI systems allow for users to configure self-hosted runner environments for perform builds and CI analysis. While both the build platform and the self-hosted runners have the ability to affect the build for the resulting artifact, the SLSA Build requirements do not need to be imposed on both systems.
This addition to the FAQ is a clarification of the requirements as they relate to the generation of the provenance.
> editorial: Clarify the requirements for self-hosted runners on provenance

- docs/spec/v1.0-rc2/terminology.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.1/terminology.md
Change Nix package ecosystem terminology to match definitions of SLSA Package model terminology. Capitalize Nix to match proper name of package ecosystem. Map SLSA Package registry to Nixpkgs (the largest repository of Nix packages [and also a Nix Flake]) and Flakes (distributed repositories of Nix packages). Map SLSA Package name to attributes of Nixpkgs and Flake outputs. Map SLSA Package artifact to Nix Store Path.
> editorial: update mapping of Nix terminology to the SLSA Package model

- MAINTAINERS.md
Adds details about maintainers moving to emeritus status
- Automatically become emeritus after some months without being active
- Defines what it means to be active
- Puts a lower bound on the number of maintainers
> impl: Add rules for moving maintainers to emeritus status.

- README.md
- controls/policy.md
- docs/_posts/2022-05-02-slsa-sbom.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.1/terminology.md
Markdown lint v0.38.0 has some changes which result in new warnings for MD0030 and MD0045 that weren't triggered prior to the update.
- MD030/list-marker-space: is now being triggered for Markdown inside a comment block
- MD045/no-alt-text: is now being triggered for HTML <img> tags
Signed-off-by: Joshua Lock <joshua.lock@uk.verizon.com>
> fix: address new markdown-lint warnings triggered on new release

- docs/spec/v1.1/levels.md
This PR adds a separate "Build Platform Requirements" row in each table of levels.md, more clearly defining what SW producers vs. build platform are responsible for at each level. To be clear, the requirements themselves have not changed, but rather the row in which they appear.
This change more closely matches the current separation in requirements.md, and also facilitates adding requirements for each role in higher/newer Build Track levels.
> editorial: Separate producer from platform requirements in Levels

- docs/spec/v0.1/terminology.md
- docs/spec/v1.0-rc1/terminology.md
- docs/spec/v1.0-rc2/index.md
- docs/spec/v1.0-rc2/terminology.md
- docs/spec/v1.0/index.md
- docs/spec/v1.0/terminology.md
- docs/spec/v1.1/index.md
- docs/spec/v1.1/terminology.md
Address markdownlint warning about inconsistent markdown syntax for
tables. We almost always use a trailing `|`, so add that to the few
places where it's missing. Also disable the lint warning on Liquid
templates that markdownlint fails to parse properly.
This unblocks upgrading to markdownlint-cli v0.39 (#1021).
A future PR might switch to leading-only syntax (#1023), but that is
outside the scope of this PR.
> impl: use consistent Markdown sytnax for tables

- docs/README.md
It's not completely straightforward to compare two versions of the built
site (`_site`) since you need to scrub commit IDs and timestamps. This
commit adds a new section to docs/README.md explaining how to do this.
This is useful to do when upgrading to new versions of dependencies
(e.g. #1028) or changing templates, where you want to make sure there
are no unexpected changes.
Ideally this could be done automatically as part of our CI/CD (GitHub
Actions or Netlify), but this is a simple first step.
> impl: add instructions on how to diff builds

- docs/README.md
Commit 74452a8 added instructions to compare builds, but it had a few
bugs:
- Did not work on MacOS due to differences between BSD `sed` (Mac) and
GNU `sed` (Linux)
- To edit in-place without a backup file, GNU sed uses `-i` (no
parameter) and BSD sed uses `-i ''`. There is no cross-platform way
to do this. So instead, just use a backup file (`-i.bak`) then
delete it afterward.
- `\+` is a GNU extension to basic regexp. Switch to extended regexp
(`-r`) which works on GNU sed and modern BSD sed.
- Incorrectly edited all dates instead of just the first. Only the first
is the build timestamp (`site.time` in Jekyll). The rest are
deterministic and should not be scrubbed. Use the `1` sed range to
fix.
- Did not note that the bash `**/*` syntax requires `shopt -s globstar`.
Signed-off-by: Mark …
> impl: fix comparison instructions

- docs/community.md
We've agreed to cancel the monthly community meeting and roll it into the weekly specification SIG meeting. Additionally, the tooling SIG has not met regularly for some time. This PR makes the following changes to the community page to reflect our new schedule:
- Archive the meeting notes for both the community meeting and the tooling SIG meeting.
- Direct contributors to the weekly specification meeting.
#1036
> nonspec: Update meeting schedule on the community page.

- docs/notes/index.md
Make the meeting notes easier to find by moving all of the old meeting
notes to a "retired" section and renaming the single remaining meeting
to "weekly Monday meeting".
Also clean up the wording in the intro and use a proper Jekyll layout to
fix the styling.
> nonspec: clean up meeting notes page

- docs/spec/v1.1/about.md
When visiting slsa.dev/spec/$version/about, I didn't see any mention of what the SLSA acronym actually stands for.
This change simply expands the acronym in the docs.
> editorial: Expand SLSA acronym in docs

- CONTRIBUTING.md
Add instructions for checking markdown formatting using markdownlint-cli2.
I got tired of getting errors after sending and updating PRs but didn't know how to run the style checker locally. Once I figured it out I suspected other folks might have a similar problem.
> nonspec: add instructions for checking markdown formatting

- MAINTAINERS.md
I'd like to self-nominate for maintainer status of the SLSA spec. I believe I meet the [criteria](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer) for maintainer status. Thanks!
> nonspec: Add Marcela as new SLSA spec maintainer

- docs/spec/draft/verifying-source.md
I noticed that the jekyll build was producing an error because the `description` variable in the front matter of the `verifying-source.md` file contained multiple lines. This fixes the format so that there is no longer any error and as a consequence the page title is now displayed correctly.
However, I must admit that although every page contains a description I cannot find whether it is actually used anywhere...
> impl: Fix Jekyll front matter

- .markdownlint.yaml
- docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
1. Only check for duplicate headings in siblings. It's useful to have allow duplicated headings that aren't in siblings to let docs have parallel construction across the entire doc.
2. Remove absolute references to slsa.dev
> fix: Fix linter errors from blog post.

- docs/spec/draft/threats.md
This patch focuses on merely editorial changes such as moving sections around and changing 'out of scope' to 'not currently addressed'.
There are a lot more TODOs to go through but that's a first step...
> editorial: Address some of the TODOs in threats and mitigation section

- CONTRIBUTING.md
Suggest PR authors assign specific reviewers and ping the Slack
channel if they want.
The goal is to make it more clear who is expected to take the next
action on PRs vs the current situation where the maintainers may
think someone else will take a look or that they may have missed
the initial PR request.
fixes #1149
> nonspec: Suggest people assign reviewers to PRs

- docs/spec/draft/source-requirements.md
The use of a change management tool doesn't necessarily indicate code was reviewed.  Perhaps it's simply requiring a PR to be used or a lint checks to be run.  'managed' more precisely gets at what's happening.
fixes #1140
> content: draft: reviewed -> managed

- MAINTAINERS.md
I'd like to propose making myself a maintainer, initially scoped to the source-track if needed!
I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer).
> nonspec: add zachariahcox to maintainers group

- MAINTAINERS.md
Following discussion with @TomHennen and @mlieberman85, I'd like to propose making myself a maintainer in order to expedite PR reviews.
I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer). Having said that, feel free to disagree!
> nonspec: Add trishankatdatadog to MAINTAINERS.md

- MAINTAINERS.md
@kpk47 has been inactive for some time so I figured I'd send this to clean things up since we've had some new maintainers added recently.
However if Kris would still be interested in contributing we could drop this.
[According to our governance this PR requires majority approval](https://github.com/slsa-framework/governance/blob/main/5._Governance.md#:~:text=A%20proposed%20removal%20also%20requires%20a%20majority%20approval)
> nonspec: Remove Kris from MAINTAINERS

- docs/spec/draft/source-requirements.md
Re: https://github.com/slsa-framework/slsa/issues/1136
I'm trying to separate "branch protection" which is typically associated with SCP features from the property we want for the branches intended for consumption. I've also applied the SCS terminology we adopted in another PR.
The framing of how this can be accomplished is still a bit TBD, if we decide to adopt something like #1142 suggests, we could move the Git + GitHub/GitLab piece out? That's also where we could discuss server side pre-receive hooks etc.?
> content: draft: Clarify branch protection in source track

- docs/spec/draft/verifying-artifacts.md
- docs/spec/draft/verifying-systems.md
These pages previously had links to the old threats page.
Updated them to reference the corresponding new threats.
fixes #1189
> fix: draft: Fix threat links in verifying-systems, verifying-artifacts

- docs/spec/draft/source-requirements.md
This follows the pattern from requirements.md where each requirement is listed along with what level it applies at.
I separate 'platform requirements' from 'change management tool' requirements to mirror the 'Provenance generation' / "Isolation strength" from requirements.md.
Future PRs will add a summary like the 'Build levels' table from requirements.md.
Refs #1069
> style: Put detailed requirements into table form

- docs/spec/draft/source-requirements.md
Clarify what type of data source level 3 provides to policy enforcement tools.
'authenticatable and auditable' is more easily understood by the community than 'reliable'.  It's also less prone to misinterpretation than 'verifiable' which might sound like a much more thorough process has been done.
fixes #1137
> content: draft: reliable -> authenticatable and auditable

- docs/spec/draft/source-requirements.md
In PR #1171 we replaced 'Source Control Platform' with 'Source Control System'.  It looks like we missed a 'Platform' usage.  This replaces that last 'Platform' with 'System'
> content: draft: Last 'Platform' -> 'System'

- docs/_data/nav/draft.yml
- docs/spec/draft/attested-build-env-levels.md
- docs/spec/draft/terminology.md
This PR introduces the following spec changes associated with https://github.com/slsa-framework/slsa/issues/975. The spec enhancements are being proposed as the new "build Environment track".
Spec changes: Adds new high-level build environment terminology and levels.
Part 1 of https://github.com/slsa-framework/slsa/issues/975 CC @paveliak
> content: draft: Add attested build environment track

- docs/spec/draft/source-requirements.md
My read is that "the present context" is what branches or tags point at the given revision.  Making that explicit.
fixes #1138
> content: draft: clarify "in the present context"

- docs/spec/draft/threats.md
These threats generally match the threats for 'Artifact Publication' with
the twist that the consumer must do the verification instead.
Explicitly calling out that modification in transit to the consumer is in scope for this threat.
Consumer verification may be simplified if a VSA was issued at publication time.
fixes https://github.com/slsa-framework/slsa/issues/1180
> content: draft: Flesh out 'Distribution Channel' threats.

- docs/spec/draft/threats.md
There are two ways to look at the usage threat:
1. Can the attacker modify the software being delivered to a consumer.
2. Can the consumer use the software insecurly allowing an attacker
to take advantage of that insecurity to exploit them.
IMO 1 has the same solutions as 'G' (PR https://github.com/slsa-framework/slsa/pull/1190).  I could repeat them
here under usage, but instead I've updated 'G' to include modification
in transit, and I've had 'Usage' address 2 above (albeit by just
deferring to CISA's work in this area).
fixes https://github.com/slsa-framework/slsa/issues/1182
NOTE: this PR is based on top of #1190 since the solution presented in 1190 obviates the need for addressing that here.
> content: draft: Flesh out "Usage" threat

- docs/spec/draft/source-requirements.md
We don't want to restrict strong authentication to the change management tool, but instead want it used throughout the system.  Moving the strong auth requirement there to reflect that desire.
fixes #1199.
> content: draft: move strong auth to the system section

- docs/spec/draft/threats-overview.md
The existing threats-overview page uses the old SLSA threats diagram, so the lettering was off and some threats were not addressed.
This update fixes the lettering, updates the language to use the terms used on the diagram, and adds missing threats.
fixes #1208
> content: draft: Update threat-overview table to use new threat diagram

- docs/spec/draft/source-requirements.md
fixes #1139
Per #1139, 'documented process' was somewhat confusing and could be interpreted as meaning some _prose_ documentation. I think the real aim is to ensure all the rules for making a change to a branch were followed.
So I changed the text to talk about those rules, rather than 'documented process'.  I think this is more aligned with what we're looking for?
> content: draft: reword "Change management process" requirement

- CONTRIBUTING.md
Currently CONTRIBUTING.md says that PRs that affect draft files have 'relaxed' approval requirements but does not specify what those relaxed requirements are.
This PR makes the default requirements for draft PRs explicit (only 1 reviewer, no waiting period) in an attempt to speed progress on draft changes. Approving reviewers will have the opportunity to indicate if they want additional reviewers prior to submitting these draft PRs.
We will still have strict requirements (3 approvers, 72h waiting period) when moving content from draft to rc or final status. This should allow thorough review of changes in their finished state without hampering progress on new tracks.
> nonspec: Make requirements for draft reviews more explicit

- docs/spec/draft/source-requirements.md
The 'via's didn't make sense under the new list construction
> editorial: draft: fix grammar mistake

- docs/spec/draft/source-requirements.md
fixes #1135
Hardens the 'safe-expunging-process' by:
1. Suggesting that SCSs should document and log changes when possible.
2. SCSs should use multi-party approval when possible
Also clarifies that some of these changes may need to be kept private to comply with local laws.
> content: draft: Harden 'safe-expunging-process'

- docs/spec/draft/source-requirements.md
Previously level 3 just required the provenance/attestations to be tamper-resistant but didn't require those attestations to be created at any particular time. If an SCS were to create these attestations on-demand it would leave revisions more susceptible to tampering within the SCS between the time of their production and the time of the request.
By creating the attestations contemporaneously it reduces the period of time during which a threat actor would be able to falsify this evidence.
Also changed 'Source Attestations' to 'Source Provenance' to be inline with #1204 where we call it 'Provenance' and not 'Attestations'.
fixes #1216
> content: draft: Improve strength of Source Level 3

- docs/spec/draft/source-requirements.md
minor copy edit.
Technically on GitHub, the old branch protections engine does not meet the `1.  Are discoverable by authorized users of the repo` requirement. 
Rulesets do meet the requirement.
> content: source track: minor copy edits: remove extra comma, update url to point to rules for github example

- docs/spec/draft/threats.md
The example was in the wrong place. It had been under a threat that was meant for attackers that modified signed attestations, yet it discussed replacing one valid attestation with another.
There wasn't an obivious existing threat to put this under so I created a new one.
fixes #1223
> content: draft: Moved example to a new threat.

- docs/spec/draft/principles.md
As work on the source track progresses the topic of 'identity' comes up quite a bit. There has been some confusion about what this means, that it could be that SLSA intends to require legal identities for all contributors.  That isn't the case.
Many in the open source world prefer to contribute without revealing their 'real' identities as has been practiced for many years. SLSA does not intend to change that.
This PR tries to make it clear that SLSA does not require real identities.
refs #1133
> content: draft: Add 'principle' protecting anonymous contribution in SLSA

- docs/spec/draft/threats.md
Documenting a SLSA-native and build trackccentric mitigation for Dependency Confusion attacks (#1181)
Would love to hear thoughts/opinions on the best way to reflect differing levels of adoption / maturity in native provenance verification across different ecosystems.
> content: Update mitigation section for the Dependency Confusion threat.

- docs/spec/draft/provenance.md
- docs/spec/v1.0/provenance.md
- docs/spec/v1.1/provenance.md
When clicking on Schema.Builder, the anchor would go to the table row with the builder ID instead of the builder heading. This should deconflict the anchor points to make the sidebar correctly point to the right place on the page.
The change also makes the tr ids consistent for the RunDetails section.
> fix: Correct sidebar links on provenance page

- docs/community.md
Discussion ref: https://openssf.slack.com/archives/C029E4N3DPF/p1733962123447219
> nonspec: Remove outdated link to old meeting videos

- docs/spec/draft/source-requirements.md
This should make it more clear make who is responsible for what.
Also adding a requirement for summary attestation distribution (mirroring what was done with the build track).
I'd like to merge the change management tool requirements into the 'System' Requirements table too, but it's a bigger change so I'll leave that for later.
refs #1111
> content: draft: Clean up source 'levels' table

- docs/_data/nav/draft.yml
- docs/_data/nav/v1.0.yml
- docs/_data/nav/v1.1.yml
- docs/community.md
- docs/current-activities.md
- docs/index.md
- docs/spec/draft/future-directions.md
- docs/spec/draft/onepage.md
- docs/spec/draft/threats.md
- docs/spec/v1.0/onepage.md
- docs/spec/v1.1/future-directions.md
- docs/spec/v1.1/onepage.md
- docs/spec/v1.1/threats.md
Following our ongoing discussions about questions of SLSA's current status, I quickly put together a new page for the website that outlines our current activities. This is mostly meant to be a starting point that we can improve upon as we figure out the best way to communicate our ongoing activities.
> nonspec: Create dedicated current activities page

- docs/spec/draft/source-requirements.md
Attempt at addressing #1264
cc @TomHennen and @zachariahcox
> content: Clarify types of identity management in source track

- docs/spec/draft/attested-build-env-levels.md
- docs/spec/draft/terminology.md
> editorial: Make build environment definitions linkable

- docs/how-to/how-to-orgs.md
HTML rendering does not appear to remove `.md` to "external" doc links.
Refs https://github.com/slsa-framework/slsa/pull/1283#issuecomment-2651904208
> fix(how-to-orgs): links to spec

- docs/spec/draft/future-directions.md
- docs/spec/draft/threats-overview.md
- docs/spec/draft/threats.md
fixes: https://github.com/slsa-framework/slsa/issues/1178
The threats.md file is intended to be a one-stop summary of all the threats mitigated by SLSA. 
From this page, we should plan to redirect to other parts of the documentation.
> content: source track: update source threats for draft spec

- docs/current-activities.md
In response to https://github.com/slsa-framework/slsa/issues/1272, I've expanded on the current activities related to the S2C2F/Dependency Track efforts.
> content: update Dependency Track efforts in current-activities.md

- docs/spec/draft/threats.md
We do not need to use the git-specific word "diff" here.
We just mean "change."
> content: source track: remove unnecessary git reference "diff"

- docs/spec/draft/threats.md
Adds a short pointer to the upcoming Dependency track for information on how to mitigate the "include vulnerable dependency" threat.
Fixes #1183
> content: Add mitigation for "Include vulnerable dependency" threat

- docs/current-activities.md
Per request in previous PR, adding a link to the OpenSSF SLSA Dependency Track slack channel
> nonspec: Update to add Slack channel for Dependency Track  on current-activities.md

- docs/spec/draft/threats-overview.md
- docs/spec/v1.1/threats-overview.md
fixes https://github.com/slsa-framework/slsa/issues/1213
Proposing we remove the detail relating to a mismatch between the uploaded package and its purported source revisions. 
That is _definitely bad_ but the primary threat here is that the producer changed their intent. 
This patch only covers v1.1 and vdraft.
> content: simplify description of event-stream threat

- docs/spec/draft/threats.md
The current draft threats.md has a couple of typos and obvious inaccuracies (claiming the page only talks about SLSA mitigations).
This PR addresses those issues.
> fix: Address typos in threats.md

- docs/spec/draft/threats.md
This change addresses multiple issues in threats.md.
* Don't let an attacker debug an in progress build. Fixes #1302 
* Use a separate cache for each build. refs #1303
* Leaves this issue open for further work.
* Don't reference source attestations in threats yet. Fixes #1306 
* Move "forge change metadata" to "Source Threats". Fixes #1307 
* Use an executable as a hash collision example instead of source file. Fixes #1308
> content: draft: address issues in threats.md

- docs/spec/draft/threats.md
This provides a more clear example of how a change might not be reviewable.
This use case is more common and seems like it is easier to understand vs why
a code review system would just display the cryptographic hash of a file.
fixes #1300
> content: draft: Update 'unreviewable change' to reference a JPEG

- docs/spec/draft/attested-build-env-levels.md
- docs/spec/draft/terminology.md
This PR updates the terminology page to match the updated supply chain diagram that replaced "package" with "distribution", to address [a remaining TODO](https://github.com/slsa-framework/slsa/pull/1298#discussion_r2012755028) prior to v1.1-RC2 release. Very few changes have actually been made to the original text.
Changes:
* New definition for "distribution"
* Replaced "package model" with "distribution model" and made minor textual updates to the section
* Add-on: Moved build environment model to the BuildEnv track spec
> content: draft: Update terminology to match updated supply chain diagram

- docs/spec/draft/future-directions.md
- docs/spec/draft/threats.md
Future directions talks about a 'Platform Operations Track' that would provide guidance on how to run a secure platform (e.g. ACLing, logging, secret management).  It _had_ been labeled the "_Build_ Platform Operations Track" but was referenced from areas that weren't _build_ platforms.  In fact this guidance would apply broadly for all platforms.  So, this change removes the 'build' qualifier.
It remains to be seen when/if this track will be developed.
fixes #1301
> content: draft: Just "Platform Operations Track"

- docs/spec/draft/threats.md
It was raised in the review of 1.1-RC2 that build L3 does not require provenance to be complete. Instead, it only requires the external parameters to be complete. With this requirement, it is still sufficient to mitigate an attack by SSH on the artifact as the verifier would be able to ensure that the external parameters meet expectations.
ref: https://github.com/slsa-framework/slsa/pull/1298#discussion_r2018863889
Signed-off-by: arewm <arewm@users.noreply.github.com>
> content: draft: build L3 requires complete external parameters, not provenance

- docs/index.md
The "current activities" link in the "project status" part of the main page goes to the wrong target. Make it go to the right one.
> fix: Fix link to current activities

- docs/spec/v1.1-rc2/about.md
- docs/spec/v1.1-rc2/attestation-model.md
- docs/spec/v1.1-rc2/distributing-provenance.md
- docs/spec/v1.1-rc2/levels.md
- docs/spec/v1.1-rc2/principles.md
- docs/spec/v1.1-rc2/provenance.md
- docs/spec/v1.1-rc2/terminology.md
- docs/spec/v1.1-rc2/use-cases.md
- docs/spec/v1.1-rc2/verifying-artifacts.md
This PR should introduce no change to the meaning of any sentence.
> fix: 1.1 rc2 run grammar check and fix typos. 

- docs/_data/versions.yml
Header wrongly still claims 1.0 is the current version. This fixes it.
> fix: Update current version

- docs/_includes/header.html
- docs/_includes/nav.html
We no longer have a version selector so the header should not direct the user to use it...
Plus (and more importantly) this fixes a Liquid coding bug that is silently ignored (gotta love this platform!!) and leads to linking to the wrong page.
> fix: Fix draft header

- docs/_data/nav/config.yml
- docs/_redirects
- docs/index.md
Removes the project status section which is outdated and no longer needed since we have "current activities" in the navigation bar.
Also adds some config and redirect to make the homepage more resilient to the publication of new spec versions.
> nonspec: Update home page

- docs/_redirects
The previous floating redirects were still pointing at v1.0. Updating those to point to 1.1 as well as adding a couple more.
Related to #1331
> fix: update redirects for v1.1 release

- docs/spec/draft/source-requirements.md
The prior language was not sufficiently clear about the intent.
What we're looking for is that organizations are _able_ to enforce additional change management requirements
with the SCS such that they can ensure that if a branch "intended for consumption" was updated that the change
meets their requirements.
> content: draft: simplify & clarify 'enforced change mgmt process'

- docs/spec/draft/source-requirements.md
* Indicate that when new auth tokens are added (e.g. ssh keys, PATs)
the second factor must be used.
* Indicate that token theft and stronger phishing resistance are
'future considerations'.
> content: draft: Improve 'strong auth' requirement wording

- docs/spec/draft/source-requirements.md
Simplify some of the wording about source provenance. Including content on how provenance is relevant for tags.
> content: draft: update wording of source provenance requirement

- docs/spec/draft/source-requirements.md
Currently the langauge makes it sound like they're produced for all revisions, but we really only need (or want!) them to be produced for ones the SCS wants to make claims about.
This change makes that more clear and indicates how consumers should think about revisions without VSAs.
> content: draft: Source VSAs shouldn't be produced for all revisions.

- docs/spec/draft/source-requirements.md
The content of a revision is built over time. The controls in place today may be more strict than the controls in place yesterday.
Users of existing repositories will need to be able to onboard those repositories with some understanding of
what claims are being made about prior revisions.
This is a first attempt at handling that issue.
> content: draft: Add onboarding blurb, clarify 'branch' definition.

- docs/spec/draft/source-requirements.md
Adding additional context around what it meanst to be a trusted robot to clarify the threat model around it. This should make it simpler to refer back to a trusted robot later in the spec.
> content: draft: reword the description of a trusted robot

- docs/spec/draft/source-requirements.md
After a great deal of discussion, looking at slsa.dev/threats, etc, it appears that two-party review is the strongest control we have against many of the threats listed for 'B'.
This PR introduced a 4th source level which requires two-party review of changes to protected branches.
As noted by some this is one of the first controls enterprises enable, while being a control that can be very difficult for small projects to enable.  To account for this we are making this the highest source level as 1-3 are much more easily attained by single-maintainer projects. Those projects can advance as far as possible without adopting two-party review.
To further reduce the burden of this requirement we suggest that reviews cover 'security relevant properties' to allow reviewers to focus on the most …
> content: draft: Introduce Source Level 4 - Two Party Review

- docs/README.md
I had a first brain dump about some of the internals of slsa.dev that ought to be better documented because anyone trying to publish a new version of the spec will need to know about these.
I still plan to do some additional investigation and update as necessary but I thought it'd be better to share it earlier rather than later. I invite anyone who's interested to have a look and ask any questions you may have. This will only help me add whatever else is missing and might be helpful in the future.
> nonspec: Add some documentation about the website internals

- docs/_posts/2025-04-29-slsa-source-sprint.md
Use the official correct way to spell "Red Hat".
(See https://www.redhat.com/en/about/brand/standards/naming-and-trademarks about half way down under the "Referring to Red Hat" heading.)
> fix: Company name nitpick in sprint blog by-line

- docs/spec/draft/verifying-source.md
This borrows _heavily_ from https://slsa.dev/spec/draft/verifying-artifacts attempting make changes where needed.
While we might think there is enough overlap that the two could share the same content, I think that's unlikely. There are enough cases where details differ that it would likely be more confusing.
This change DOES NOT include "Resulting threat mitigation" which is included in 'Step 1' of 'verifying-artifacts'.  We may want to include that in the future or we might prefer to leave it to the threats.md page.
refs #1356
> content: draft: Define the process for verifying source.

- docs/spec/draft/verifying-artifacts.md
- docs/spec/v1.1/verifying-artifacts.md
The 'conformance program' is no longer 'coming soon' so we shouldn't say that it is.
Updating both 1.1 (current) and draft.
As this doesn't change the meaning of the spec I've listed this as 'editorial' and I don't think we need (or should) increment the 1.1 version number.  If anyone thinks otherwise (or that we should just not update 1.1) LMK.
fixes #1364
> editorial: Remove mention of conformance program

- docs/spec/draft/source-requirements.md
Require orgs to:
1. Specify which branches and tags are protected (L2+)
2. Specify what additional controls they want users to expect (L3+)
_Allow_ orgs to define properties to be included in the VSA to communicate which controls they've enabled.
Updated the 'Enforced change management process' to be require the SCS enforce the technical controls from #2.
Moved "safe expunging process" into this table (it was an org requirement anyways). Only requiring at L2+ because that's when branch continuity comes into play anyways (prior to that folks can technically make whatever changes they want to a repo).
fixes #1361
> content: draft: Expand 'organization requirements'

- docs/spec/draft/source-requirements.md
1. Removes the 'Verified timestamp' requirement as the SLSA Source track doesn't seem to be the right place to address this.
2. Moves the 'Context' requirement up to the "Source Control System" section.
3. Removes the "Branches may have differing security postures, and a change can be approved for one context while being unapproved for another." statement as it's a) explanation rather than requirement, b) covered by other requirements that talk about how some branches need to be protected and others don't.
4. Updated the 'Context' requirement to apply at Level 2 (instead of starting at Level 3) as I believe this is a fairly basic feature of VCSes.  AIUI this requirement isn't about storing this data in provenance, just making it available.  If it _is_ about what gets encoded in …
> content: draft: Merge change mgmt tool requirements with SCS

- README.md
source track was pointing to closed issue -- should point to project board. 
1.1 shipped, current work is on 1.2, linked to issue label query? Could also link to board.
> fix: readme: update links to workstreams

- docs/spec/draft/source-requirements.md
Continuity is relevant for any requirements imposed on successive revisions within a protected branch. This PR is clarifying that continuity is established from a given revision and what properties also adhere to the continuity requirements.
This PR superseded the work in #1349 due to the amount of changes to the spec that have happened since it was opened.
> content: draft: further refinement for revision continuity

- docs/spec/draft/source-requirements.md
The current wording of the `dependencyLevels` VSA property for the source track just states that dependencies are not common. While this may be true, git submodules are not too uncommon, so we should call these out specifically as an example.
> editorial: Describe a potential use case of source `dependencyLevels`

- docs/spec/draft/source-requirements.md
As I was reading through the source track draft I noticed an extra line that was left-over from some previous editing. This deletes it.
> fix: remove left-over line

- docs/spec/draft/source-requirements.md
fixes #1410
* Example doesn't use bullets anymore. (should fix rendering issue)
* Example dropped reference to "some other mechanism as enforced by the Change management tool."
* The referenced tool doesn't exist anymore.
* The example doesn't need to be exhaustive, so it should be fine to remove.
* Added "The SCS MUST prevent organization-specified" to the other bulleted list.
* Makes it more cohesive with the other requirements
* Makes it more clear the example applies to the list, not just the "MUST prevent ..." language.
> editorial: draft: Fix formatting in "Enforced Change Management Process"

- docs/spec/draft/verifying-systems.md
- docs/spec/v1.0/verifying-systems.md
- docs/spec/v1.1-rc1/verifying-systems.md
- docs/spec/v1.1-rc2/verifying-systems.md
- docs/spec/v1.1/verifying-systems.md
fixes #1389
This link was broken pretty pervasively.  This should fix things ~everywhere.
Just a fix as no content was changed.
> fix: fix broken 'provenance model' link in 1.0, 1.1, draft, RCs

- docs/spec/draft/verification_summary.md
This basically follows the same strategy as before but provides a formula
instead of a full enumeration and links to verified-properties.md for
additional SLSA_ values.
I've decided _not_ to include a prohibition on `ORG_` prefixed policies because
the SlsaResult documentation already tells users (i.e. VSA issuers) that they
MAY use custom values as long as they don't start with `SLSA_`. `ORG_`
prefixed values, as they're defined by the organization, _are_ custom values
so it seems we're already aligned with the spec.  We're also not trying to
establish (within SLSA) any specific meaning for these ORG properties.
That's left to the org itself to document.
fixes https://github.com/slsa-framework/slsa/issues/1369
> content: draft: Update VSA spec to handle SLSA levels beyond the build track

- docs/_includes/onepage.liquid
This prefix should disambiguate the tags used in assembling this page. Unfortunately it won't ensure there aren't conflict tags elsewhere.
refs #1426
> fix: prefix anchor tag with 'onepage-'

- .devcontainer/devcontainer.json
Podman restricts access to /root unless the `--privileged` flag is passed. An alternative is to just specify a `remoteUser` and `containerUser`. This resolves an issue where the IDE might try to install additional tools into the devContainer.
> impl: add users to devcontainer

- docs/_posts/2025-06-20-slsa-v1.2-rc1.md
Not sure the dates are right. This might need adjustment when we know for sure when 1.2 RC1 gets published. But please, let me know if you'd like to change anything else.
I'll mark this as a draft until the publication is out.
> blog: Add blog post announcing 1.2 RC1

- docs/_redirects
This should make it a bit easier to tell people the links and put them on slides, etc.
Once we release 1.2 it would be nice to have just slsa.dev/source, slsa.dev/build.
> style: Add redirects for source/build

- docs/spec/draft/source-requirements.md
fixes #1460
Add a requirement at L1 that SCS's provide tooling to display changes in human readable form. Used most of the langage from 'informed review' (L4) and then having 'informed review' reference this requirement.
Note that this is a MUST for plain text files but a SHOULD for non-plain text.
> content: draft: Human Readable Changes

- .vscode/settings.json
- docs/spec/draft/source-requirements.md
While working on https://github.com/slsa-framework/slsa/pull/1483 found and addressed various small grammar, formatting and copy edit mistakes in the source track. 
Isolated them here as non-spec changes to help them merge faster.
> nonspec: source requirements copy edits
